package local.alba;
import android.app.Instrumentation;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.*;
import org.json.*;
import java.lang.reflect.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

/** UI fixtures only. No real credentials, Telegram messages or model claims. */
public final class NativeUiSmoke extends Instrumentation {
    private MainActivity activity;
    private JSONObject fixtures;
    private FakeApi fake;
    private Throwable failure;
    private int checks=0;
    public void onCreate(Bundle arguments){super.onCreate(arguments);start();}
    public void onStart(){new Thread(()->{
        Bundle result=new Bundle();try{
            byte[] data=new byte[65536];int count;StringBuilder json=new StringBuilder();try(java.io.InputStream in=getContext().getAssets().open("fixture.json")){while((count=in.read(data))!=-1)json.append(new String(data,0,count,"UTF-8"));}fixtures=new JSONObject(json.toString());
            getTargetContext().getSharedPreferences("alba",0).edit().putBoolean("light_theme",false).commit();activity=(MainActivity)startActivitySync(new Intent(Intent.ACTION_MAIN).setClassName("local.alba","local.alba.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
            ((ExecutorService)field("io")).submit(()->{}).get(35,TimeUnit.SECONDS);waitForIdleSync();
            JSONObject fixtureContent=fixtures.getJSONObject("note").getJSONObject("content");fixtureContent.put("font","custom");fixtureContent.put("font_size",28);fixtureContent.put("letter_spacing",-.5);fixtureContent.put("html","<p>AAA original text.</p>");fixtureContent.put("custom_font",new JSONObject("{\"name\":\"Giada\",\"weight\":10,\"glyphs\":{\"A\":[[[70,240],[150,40],[230,240]]]}}"));
            fake=new FakeApi();ui(()->{set("api",fake);set("english",true);call("signedIn",new Class[]{JSONObject.class},new JSONObject().put("name","Smoke").put("user_id",1).put("is_admin",true));});settle();
            ui(()->{fake.failNotte=true;call("navigate",new Class[]{int.class},1);});settle();ui(()->{check(visible("A native answer."),"Alba works when Notte status is unavailable");fake.failNotte=false;call("navigate",new Class[]{int.class},2);call("openNote",new Class[]{int.class},1);call("navigate",new Class[]{int.class},0);});settle();ui(()->check(field("note")==null&&field("composer")!=null,"Late notebook response cannot replace the active chat"));
            capture("chat");ui(()->{assertNative(activity.getWindow().getDecorView());check(visible("A native answer."),"Native markdown answer");check(hasClass(activity.getWindow().getDecorView(),TableLayout.class),"Native markdown table");((EditText)field("composer")).setText("Unsent draft");call("navigate",new Class[]{int.class},4);});settle();
            ui(()->{check(visible("Verified function."),"Topic diary");call("navigate",new Class[]{int.class},0);});settle();
            ui(()->{check(((EditText)field("composer")).getText().toString().equals("Unsent draft"),"Chat draft survives menu");call("navigate",new Class[]{int.class},6);});settle();
            ui(()->{check(visible("Personal Qwen · CPU training"),"Native model panel");call("navigate",new Class[]{int.class},8);});settle();
            ui(()->{check(visible("Raspberry Pi"),"Native system panel");call("navigate",new Class[]{int.class},5);});settle();
            ui(()->{check(visible("#1 · chat · assistant"),"All activity panel");call("navigate",new Class[]{int.class},11);});settle();
            ui(()->{check(visible("Same model and prompt"),"Native Test Lab panel");check(hasClass(activity.getWindow().getDecorView(),NativeBars.class),"Native measured bar charts");JSONArray failed=new JSONArray().put(new JSONObject().put("backend","optimized").put("status","error").put("wall_ms",84));String failedSvg=new NativeBars(activity,failed,"wall_ms","Total wait","ms",true).svg();check(failedSvg.contains("N/A")&&!failedSvg.contains("<rect"),"Failed runtime is not plotted as fast");((EditText)field("labPrompt")).setText("Lab draft survives polling");call("poll",new Class[]{});});settle();
            ui(()->{check(((EditText)field("labPrompt")).getText().toString().equals("Lab draft survives polling"),"Live lab polling preserves prompt input");call("runLab",new Class[]{});});settle();
            ui(()->{check(fake.labSubmitted!=null&&fake.labSubmitted.optString("mode").equals("compare"),"Lab sends an explicit compare request");check(fake.labSubmitted.optString("model").equals("qwen2.5-coder:7b"),"Lab uses selected installed target");check(fake.labSubmitted.optString("policy").equals("adaptive"),"Lab submits chosen adaptive optimization after standard");call("navigate",new Class[]{int.class},12);});settle();
            ui(()->{check(visible("Local test bench"),"Native project evolution entries");call("navigate",new Class[]{int.class},2);call("openNote",new Class[]{int.class},1);});settle();
            ui(()->{EditText editor=(EditText)field("noteText");check(editor.getText().getSpans(0,editor.length(),PersonalFont.Glyph.class).length==3,"Saved Giada glyphs rendered natively; other letters fall back");check(Math.abs(editor.getTextSize()/activity.getResources().getDisplayMetrics().scaledDensity-28)<.1,"Native saved text size");check(Math.abs(editor.getLetterSpacing()+.5/28)<.001,"Native saved letter spacing");check(visible("Giada"),"Page displays saved font name");((EditText)field("noteTitle")).setText("Changed title only");JSONObject titleOnly=(JSONObject)call("noteData",new Class[]{});check(titleOnly.getJSONObject("content").optString("html").equals(fixtureContent.optString("html")),"Title change preserves exact original HTML");check(editor instanceof NotebookText,"Ruled text uses actual editable line metrics");check(((View)field("body")).findViewWithTag("page-navigation")!=null,"Page controls are immediately reachable");call("chooseFont",new Class[]{});});settle();capture("fonts");click("Victor");settle();
            ui(()->{check(((JSONObject)field("note")).getJSONObject("content").getJSONObject("custom_font").optString("name").equals("Victor"),"Named preset selectable from Android notebook");call("chooseFont",new Class[]{});});settle();click("Giada");settle();ui(()->call("showEditorPane",new Class[]{boolean.class},true));waitForIdleSync();
            capture("drawing");ui(()->{NotebookCanvas canvas=(NotebookCanvas)field("canvas");check(canvas.getHeight()>activity.getResources().getDisplayMetrics().heightPixels*.35,"Drawing has a usable viewport");check(((View)field("textPane")).getVisibility()==View.GONE,"Text hidden while drawing");canvas.strokes.put(new JSONObject("{\"tool\":\"pen\",\"color\":\"#213a2b\",\"size\":3,\"points\":[[200,320],[800,320]]}"));String original=canvas.strokes.toString();canvas.setEraser(true);android.view.MotionEvent down=android.view.MotionEvent.obtain(0,0,android.view.MotionEvent.ACTION_DOWN,canvas.getWidth()/2f,canvas.getHeight()/2f,0),up=android.view.MotionEvent.obtain(0,1,android.view.MotionEvent.ACTION_UP,canvas.getWidth()/2f,canvas.getHeight()/2f,0);canvas.onTouchEvent(down);canvas.onTouchEvent(up);down.recycle();up.recycle();check(canvas.strokes.length()==2,"Native eraser splits a crossing line without deleting all ink");canvas.undo();check(canvas.strokes.toString().equals(original),"Native undo restores erased ink");canvas.setEraser(false);int height=canvas.getHeight();set("rendered",Integer.toString(height));call("setDrawingFocus",new Class[]{boolean.class},true);});waitForIdleSync();
            ui(()->{check(((NotebookCanvas)field("canvas")).getHeight()>Integer.parseInt((String)field("rendered")),"Fullscreen expands drawing");check(((View)field("bottomNav")).getVisibility()==View.GONE,"Fullscreen hides navigation");call("back",new Class[]{});check(!((Boolean)field("drawingFocus")),"Back exits fullscreen without discarding note");call("showEditorPane",new Class[]{boolean.class},false);});waitForIdleSync();
            capture("font");ui(()->{EditText fastEditor=(EditText)field("noteText");PersonalFont.Glyph firstGlyph=fastEditor.getText().getSpans(0,fastEditor.length(),PersonalFont.Glyph.class)[0];fastEditor.append(" Edited.");check(fastEditor.getText().getSpans(0,fastEditor.length(),PersonalFont.Glyph.class)[0]==firstGlyph,"Typing preserves glyphs outside the edited range");JSONObject saved=(JSONObject)call("noteData",new Class[]{});JSONObject original=fixtures.getJSONObject("note").getJSONObject("content"),content=saved.getJSONObject("content");check(content.getJSONObject("graph").toString().equals(original.getJSONObject("graph").toString()),"Graph survives native text editing");check(content.getJSONArray("formulas").toString().equals(original.getJSONArray("formulas").toString()),"Formula survives native text editing");check(content.getJSONObject("network").toString().equals(original.getJSONObject("network").toString()),"Network survives native text editing");check(content.optString("html").contains("Edited."),"Text edits are saved after metadata-only changes");call("saveNote",new Class[]{});});settle();
            ui(()->{check(fake.saved.getJSONObject("content").getJSONObject("custom_font").optString("name").equals("Giada"),"Font snapshot survives save");check(fake.saved.getJSONObject("content").optDouble("font_size")==28,"Size survives save");check(((EditText)field("noteText")).getText().getSpans(0,((EditText)field("noteText")).length(),PersonalFont.Glyph.class).length==3,"Font remains while editing");});
            ui(()->{check(!((Boolean)field("noteChanged")),"Native save clears dirty state");check(fake.saved!=null&&fake.saved.optInt("version")==1,"Optimistic version is sent");((EditText)field("noteText")).append(" Saved before leaving.");call("navigate",new Class[]{int.class},0);});settle();click("Save & leave");settle();ui(()->{check(field("note")==null&&field("composer")!=null,"Save and leave waits for successful persistence");check(fake.saved.optInt("version")==2,"Save and leave uses the latest page version");set("english",false);call("navigate",new Class[]{int.class},9);check(visible("Lingua dell’app"),"Italian UI");set("note",null);set("noteChanged",false);call("navigate",new Class[]{int.class},0);call("menu",new Class[]{});});waitForIdleSync();
            ui(()->check(((String[])call("sections",new Class[]{}))[4].equals("Diario di apprendimento"),"Dropdown section names"));click("Chiudi");settle();ui(()->{set("english",true);call("menu",new Class[]{});});capture("menu");click("Close");ui(()->set("english",false));settle();
            ui(()->{call("navigate",new Class[]{int.class},0);((EditText)field("composer")).setText("Notte draft");Intent link=new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://fixture.invalid/"));call("onNewIntent",new Class[]{Intent.class},link);check(link.getData()==null,"Warm link URI cleared");check(((Integer)field("section"))==1,"Warm link switches native section");check(((EditText)field("composer")).getText().toString().isEmpty(),"Warm link does not copy another channel draft");call("navigate",new Class[]{int.class},0);check(((EditText)field("composer")).getText().toString().equals("Notte draft"),"Warm link preserves source draft");Intent bad=new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://evil.invalid/notte#web_key=secret"));call("intent",new Class[]{Intent.class},bad);check(bad.getData()==null&&((String)field("pendingKey")).isEmpty(),"External server key rejected and cleared");call("persistDrafts",new Class[]{});set("job","old-account-job");call("signedIn",new Class[]{JSONObject.class},new JSONObject().put("user_id",2).put("is_admin",true));check(((String[])field("drafts"))[0].isEmpty(),"Account switch clears private drafts");check(((String)field("job")).isEmpty(),"Account switch clears in-flight job from previous account");});settle();
            ui(()->{set("english",true);call("navigate",new Class[]{int.class},2);});settle();capture("library");ui(()->{check(visible("Ideas and projects"),"Real notebook cards render");check(visible("2 / 10 saved presets"),"Saved font collection visible from library");call("openNote",new Class[]{int.class},1);});settle();ui(()->call("paperOptions",new Class[]{}));settle();click("Grid");settle();ui(()->{check(((JSONObject)field("note")).getJSONObject("content").optString("paper").equals("grid"),"Paper selection updates shared page content");((EditText)field("noteText")).append(" Theme draft.");});
            android.content.SharedPreferences prefs=getTargetContext().getSharedPreferences("alba",0);String originalServer=prefs.getString("server",getTargetContext().getString(R.string.default_server));prefs.edit().putString("server","https://fixture.invalid").apply();
            ActivityMonitor monitor=addMonitor(MainActivity.class.getName(),null,false);ui(()->call("changeTheme",new Class[]{}));android.app.Activity next=waitForMonitorWithTimeout(monitor,10000);removeMonitor(monitor);if(next==null)throw new AssertionError("Theme did not recreate the activity");activity=(MainActivity)next;((ExecutorService)field("io")).submit(()->{}).get(35,TimeUnit.SECONDS);waitForIdleSync();fake=new FakeApi();ui(()->{set("api",fake);set("english",true);call("signedIn",new Class[]{JSONObject.class},new JSONObject().put("user_id",2).put("is_admin",true));check(new NativeUi(activity).light,"Light theme persists after recreation");check(((EditText)field("noteText")).getText().toString().contains("Theme draft."),"Theme change preserves unsaved page draft");check(((JSONObject)field("note")).getJSONObject("content").optString("paper").equals("grid"),"Theme change preserves paper style");check(((EditText)field("noteText")).getText().getSpans(0,((EditText)field("noteText")).length(),PersonalFont.Glyph.class).length==3,"Theme change preserves personal font rendering");call("showEditorPane",new Class[]{boolean.class},true);});settle();capture("light-drawing");ui(()->call("showEditorPane",new Class[]{boolean.class},false));settle();capture("light-text");ui(()->{call("saveNote",new Class[]{});});settle();ui(()->call("navigate",new Class[]{int.class},9));settle();capture("light-settings");ui(()->call("menu",new Class[]{}));settle();capture("light-menu");click("Close");prefs.edit().putString("server",originalServer).apply();
            ui(()->{call("navigate",new Class[]{int.class},2);call("openNote",new Class[]{int.class},1);});settle();ui(()->{((EditText)field("noteText")).append(" Autosave marker.");});Thread.sleep(2200);settle();ui(()->{check(!((Boolean)field("noteChanged")),"Debounced autosave completes");check(fake.saved.getJSONObject("content").optString("html").contains("Autosave marker."),"Autosave persists final text");call("back",new Class[]{});});settle();ui(()->{check(field("note")==null,"Back clears the previous notebook page");check(visible("Fixture page"),"Back returns to searchable page index");call("back",new Class[]{});});settle();ui(()->{check(visible("Ideas and projects"),"Page index returns to notebook library");call("navigate",new Class[]{int.class},1);});settle();ui(()->{LinearLayout feed=(LinearLayout)field("feed");JSONArray rows=new JSONArray(fixtures.getJSONObject("events").getJSONArray("events").toString());while(rows.length()<3)rows.put(new JSONObject().put("role","assistant").put("content","Initial message "+rows.length()));call("renderChat",new Class[]{JSONArray.class},rows);View first=feed.getChildAt(0);rows.put(new JSONObject().put("role","assistant").put("content","Another message"));call("renderChat",new Class[]{JSONArray.class},rows);check(feed.getChildAt(0)==first,"Chat append preserves existing message views");((EditText)field("composer")).setText("Send this");call("send",new Class[]{});((EditText)field("composer")).setText("Keep my next draft");});settle();ui(()->{check(((EditText)field("composer")).getText().toString().equals("Keep my next draft"),"Sending preserves text typed during the request");});
            if(failure!=null)throw new RuntimeException(failure);
            checks+=NativeTransportChecks.run(getTargetContext());
            documentationScreenshots();
            prefs.edit().putBoolean("light_theme",false).apply();
            result.putString("stream","PASS: "+checks+" native UI checks; fixture API; no browser views\n");finish(-1,result);
        }catch(Throwable error){java.io.StringWriter trace=new java.io.StringWriter();error.printStackTrace(new java.io.PrintWriter(trace));result.putString("stream","FAIL after "+checks+" checks: "+trace+"\n");finish(0,result);}
    },"native-smoke").start();}
    private void settle() throws Exception {((ExecutorService)field("pollIo")).submit(()->{}).get(10,TimeUnit.SECONDS);((ExecutorService)field("io")).submit(()->{}).get(10,TimeUnit.SECONDS);waitForIdleSync();Thread.sleep(150);waitForIdleSync();if(failure!=null)throw new RuntimeException(failure);}
    /** Real English UI captures with public sample content, after all assertions. */
    private void documentationScreenshots() throws Exception {
        ui(()->{
            set("english",true);set("note",null);set("noteChanged",false);set("job","");
            fake.documentation=true;
            fixtures.getJSONObject("note").put("title","Ideas for tomorrow").put("page_number",1);
            JSONObject content=fixtures.getJSONObject("note").getJSONObject("content");
            content.put("font","serif").put("font_size",18).put("letter_spacing",0).put("paper","ruled");
            content.put("html","<p>Make room for a fresh idea.</p><p>Write a little every day. Keep the useful details together.</p><p>Today’s plan:<br>Sketch the first version.<br>Read, revise, and try again.</p>");
            content.put("formulas",new JSONArray());
            fixtures.getJSONObject("events").put("events",new JSONArray()
                .put(new JSONObject().put("id",1).put("role","user").put("content","Help me organize my notes.").put("created",1791119976))
                .put(new JSONObject().put("id",2).put("role","assistant").put("content","Start with one notebook for each project.\n\nGive each page a short title, then keep your ideas, sketches, and next steps together.\n\nWe can take it one page at a time.").put("emotion","curiosity / care").put("created",1791119977)));
            call("navigate",new Class[]{int.class},2);call("openNote",new Class[]{int.class},1);
        });settle();Thread.sleep(3500);capture("docs-notebook");
        ui(()->{set("note",null);set("noteChanged",false);call("navigate",new Class[]{int.class},2);});settle();capture("docs-library");
        ui(()->{String[] drafts=(String[])field("drafts");for(int i=0;i<drafts.length;i++)drafts[i]="";call("navigate",new Class[]{int.class},0);});settle();capture("docs-chat");
    }
    private void capture(String name) throws Exception {Thread.sleep(450);waitForIdleSync();android.graphics.Bitmap bitmap=getUiAutomation().takeScreenshot();if(bitmap==null)throw new AssertionError("Screenshot unavailable");try(java.io.FileOutputStream out=new java.io.FileOutputStream(new java.io.File(getTargetContext().getExternalFilesDir(null),"smoke-"+name+".png"))){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}
    private void click(String text) throws Exception {for(int retry=0;retry<20;retry++){Thread.sleep(200);android.view.accessibility.AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();if(root==null)continue;for(android.view.accessibility.AccessibilityNodeInfo node:root.findAccessibilityNodeInfosByText(text)){android.graphics.Rect bounds=new android.graphics.Rect();node.getBoundsInScreen(bounds);if(bounds.isEmpty()||!node.isVisibleToUser())continue;long now=android.os.SystemClock.uptimeMillis();android.view.MotionEvent down=android.view.MotionEvent.obtain(now,now,android.view.MotionEvent.ACTION_DOWN,bounds.centerX(),bounds.centerY(),0),up=android.view.MotionEvent.obtain(now,now+50,android.view.MotionEvent.ACTION_UP,bounds.centerX(),bounds.centerY(),0);down.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);up.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);boolean clicked=getUiAutomation().injectInputEvent(down,true)&&getUiAutomation().injectInputEvent(up,true);down.recycle();up.recycle();if(clicked)return;}if(retry%2==1)scrollList(root);}capture("font-choices");throw new AssertionError("Cannot select "+text+"; active window: "+windowText(getUiAutomation().getRootInActiveWindow()));}
    private boolean scrollList(android.view.accessibility.AccessibilityNodeInfo node){if(node==null)return false;if("android.widget.ListView".contentEquals(node.getClassName())&&node.isScrollable()&&node.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_SCROLL_FORWARD))return true;for(int i=0;i<node.getChildCount();i++)if(scrollList(node.getChild(i)))return true;return false;}
    private String windowText(android.view.accessibility.AccessibilityNodeInfo node){if(node==null)return "none";StringBuilder out=new StringBuilder();if(node.getText()!=null)out.append(node.getText()).append(" | ");if(node.getContentDescription()!=null)out.append(node.getContentDescription()).append(" | ");for(int i=0;i<node.getChildCount()&&out.length()<3000;i++)out.append(windowText(node.getChild(i)));return out.toString();}
    private interface Task {void run() throws Exception;}
    private void ui(Task task){runOnMainSync(()->{try{task.run();}catch(Throwable e){failure=e;}});}
    private Object field(String name) throws Exception {Field field=MainActivity.class.getDeclaredField(name);field.setAccessible(true);return field.get(activity);}
    private void set(String name,Object value) throws Exception {Field field=MainActivity.class.getDeclaredField(name);field.setAccessible(true);field.set(activity,value);}
    private Object call(String name,Class[] types,Object... args) throws Exception {Method method=MainActivity.class.getDeclaredMethod(name,types);method.setAccessible(true);return method.invoke(activity,args);}
    private void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}
    private boolean visible(String text){return contains(activity.getWindow().getDecorView(),text);}
    private boolean contains(View view,String text){if(view instanceof TextView&&((TextView)view).getText().toString().contains(text))return true;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)if(contains(((ViewGroup)view).getChildAt(i),text))return true;return false;}
    private boolean hasClass(View view,Class type){if(type.isInstance(view))return true;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)if(hasClass(((ViewGroup)view).getChildAt(i),type))return true;return false;}
    private void assertNative(View view){check(!view.getClass().getName().startsWith("android.webkit."),"No browser views");if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)assertNative(((ViewGroup)view).getChildAt(i));}
    private final class FakeApi extends NativeApi {
        JSONObject saved,labSubmitted;
        boolean failNotte=false,documentation=false;
        FakeApi() throws Exception {super(getTargetContext(),"https://fixture.invalid");}
        @Override synchronized JSONObject request(String method,String path,JSONObject body) throws Exception {
            if(path.equals("/api/tramonto/fonts")){JSONObject font=fixtures.getJSONObject("note").getJSONObject("content").getJSONObject("custom_font");return new JSONObject().put("fonts",new JSONArray().put(new JSONObject().put("id","giada").put("font",font)).put(new JSONObject().put("id","victor").put("font",new JSONObject(font.toString()).put("name","Victor"))));}
            if(path.equals("/api/notte/status")){if(failNotte)throw new Failure(503,"Notte unavailable");return fixtures.getJSONObject("status");}
            if(path.equals("/api/history"))return new JSONObject().put("messages",fixtures.getJSONObject("events").getJSONArray("events"));
            if(path.equals("/api/notte/models"))return fixtures.getJSONObject("models");
            if(path.equals("/api/notte/project"))return fixtures.getJSONObject("project");
            if(path.equals("/api/notte/lab")&&method.equals("POST")){labSubmitted=body;return new JSONObject("{\"ok\":true}");}
            if(path.startsWith("/api/notte/events"))return fixtures.getJSONObject("events");
            if(path.equals("/api/notte/diary"))return fixtures.getJSONObject("diary");
            if(path.startsWith("/api/tramonto/notes?notebook="))return new JSONObject().put("notes",new JSONArray().put(new JSONObject().put("id",1).put("title",documentation?"Ideas for tomorrow":"Fixture page").put("page_number",1).put("subject",documentation?"general":"generale")));
            if(path.equals("/api/tramonto/notebooks"))return new JSONObject("{\"notebooks\":[{\"id\":1,\"title\":\"Ideas and projects\",\"note_count\":12},{\"id\":2,\"title\":\"Drawings\",\"note_count\":8}]}");
            if(path.equals("/api/tramonto/notes/1")){if(method.equals("PUT")){saved=body;return new JSONObject().put("version",body.getInt("version")+1);}return new JSONObject(fixtures.getJSONObject("note").toString());}
            return new JSONObject("{\"ok\":true}");
        }
    }
}
