'use strict';
let language=localStorage.getItem('notte.project.language')||(navigator.language.startsWith('it')?'it':'en'),project;
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
const tr=(it,en)=>language==='it'?it:en;
function chart(rows){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 660 230');svg.setAttribute('role','img');svg.setAttribute('aria-label',tr('Velocità per prompt: mapped e draft verificato, token al secondo','Prompt speed: mapped and verified draft, tokens per second'));
 const put=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;svg.append(e);return e;},maximum=Math.max(1,...rows.flatMap(r=>[r.normal,r.optimized]));
 rows.forEach((r,i)=>{const y=22+i*58;put('text',{x:0,y:y+12,class:'chart-label'},r.name);for(const [j,value] of [r.normal,r.optimized].entries()){const bar=put('rect',{x:140,y:y+j*20,width:value/maximum*410,height:14,rx:3,class:j?'bar-optimized':'bar-normal'}),title=document.createElementNS(ns,'title');title.textContent=(j?'Draft':'Mapped')+' '+value.toFixed(3)+' token/s';bar.append(title);put('text',{x:555,y:y+j*20+12,class:'chart-label'},value.toFixed(2));}});
 put('text',{x:140,y:220,class:'chart-muted'},tr('Grigio: mapped · Salvia: draft verificato · token/s, più alto = più veloce','Gray: mapped · Sage: verified draft · tokens/s, higher = faster'));return svg;
}
function render(){
 document.documentElement.lang=language;document.getElementById('language').value=language;document.querySelectorAll('[data-it]').forEach(el=>el.textContent=el.dataset[language]);if(!project)return;
 const entries=project.history.entries||[];
 for(const id of ['newsItems','historyItems'])document.getElementById(id).replaceChildren(...entries.map(entry=>{const card=node('article',undefined,'card');card.append(node('p',entry.date+' · '+entry.version+' · '+entry.status,'badge'),node('h3',entry['title_'+language]),node('p',entry['body_'+language]));const a=node('a',tr('Leggi documentazione →','Read documentation →'));a.href=entry.report?'/optimization/reports/'+encodeURIComponent(entry.report):entry.url;card.append(a);return card;}));
 const records=project.measurements.results||[],find=policy=>[...records].reverse().find(r=>r.model==='qwen2.5-coder:7b'&&r.options.ssd_policy===policy&&r.metrics.cache==='native-runtime'),normal=find('mapped'),optimized=find('speculative');
 if(normal&&optimized){const rows=['python','logic','english'].map(topic=>({name:({python:'Python',logic:tr('Aritmetica','Arithmetic'),english:tr('Inglese','English')})[topic],normal:normal.metrics.samples.find(s=>s.topic===topic&&s.cache==='warm').tokens_per_second,optimized:optimized.metrics.samples.find(s=>s.topic===topic&&s.cache==='warm').tokens_per_second}));document.getElementById('publicChart').replaceChildren(chart(rows));const table=node('table'),head=node('tr');[tr('Prova','Probe'),'Mapped token/s','Draft token/s',tr('Variazione','Change')].forEach(text=>head.append(node('th',text)));table.append(head);for(const r of rows){const line=node('tr');[r.name,r.normal.toFixed(3),r.optimized.toFixed(3),((r.optimized/r.normal-1)*100).toFixed(1)+'%'].forEach(text=>line.append(node('td',text)));table.append(line);}document.getElementById('benchmarkTable').replaceChildren(table);}
}
document.getElementById('language').onchange=e=>{language=e.target.value;localStorage.setItem('notte.project.language',language);render();};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));for(const id of ['info','news','benchmarks','history'])document.getElementById(id).hidden=id!==button.dataset.view;});
render();fetch('/optimization/data',{credentials:'omit'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(value=>{project=value;render();}).catch(()=>document.getElementById('status').textContent=tr('Dati non disponibili. Riprova più tardi.','Data unavailable. Try again later.'));
