'use strict';
let language=localStorage.getItem('notte.project.language')||(navigator.language.startsWith('it')?'it':'en'),project;
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
const tr=(it,en)=>language==='it'?it:en;
function chart(rows){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 660 230');svg.setAttribute('role','img');svg.setAttribute('aria-label',tr('Velocità per prompt: mapped e draft verificato, token al secondo','Prompt speed: mapped and verified draft, tokens per second'));
 const put=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;svg.append(e);return e;},maximum=Math.max(1,...rows.flatMap(r=>[r.normal,r.optimized]));
 rows.forEach((r,i)=>{const y=22+i*58;put('text',{x:0,y:y+12,class:'chart-label'},r.name);for(const [j,value] of [r.normal,r.optimized].entries()){const bar=put('rect',{x:140,y:y+j*20,width:value/maximum*410,height:14,rx:3,class:j?'bar-optimized':'bar-normal'}),title=document.createElementNS(ns,'title');title.textContent=(j?'Draft':'Mapped')+' '+value.toFixed(3)+' token/s';bar.append(title);put('text',{x:555,y:y+j*20+12,class:'chart-label'},value.toFixed(2));}});
 put('text',{x:140,y:220,class:'chart-muted'},tr('Grigio: mapped · Salvia: draft verificato · token/s, più alto = più veloce','Gray: mapped · Sage: verified draft · tokens/s, higher = faster'));return svg;
}
function render(){
 document.documentElement.lang=language;document.getElementById('language').value=language;document.querySelectorAll('[data-it]').forEach(el=>el.textContent=el.dataset[language]);if(!project)return;
 const entries=project.history.entries||[];
 for(const id of ['newsItems','historyItems'])document.getElementById(id).replaceChildren(...entries.map(entry=>{const card=node('article',undefined,'card');card.append(node('p',entry.date+' · '+entry.version+' · '+entry.status,'badge'),node('h3',entry['title_'+language]),node('p',entry['body_'+language]));const a=node('a',tr('Leggi documentazione →','Read documentation →'));a.href=entry.report?'/optimization/reports/'+encodeURIComponent(entry.report):entry.url;card.append(a);return card;}));
 const adaptive=node('table'),heading=node('tr');[tr('Strategia / prova','Strategy / probe'),'Standard s',tr('Ottimizzato s','Optimized s'),tr('Controllo','Check')].forEach(text=>heading.append(node('th',text)));adaptive.append(heading);
 for(const r of project.adaptive_measurements?.results||[]){const line=node('tr'),a=r.samples.find(s=>s.backend==='normal'),b=r.samples.find(s=>s.backend==='optimized'),seconds=s=>s?.status==='ok'?(s.wall_ms/1000).toFixed(2):'N/A',passed=s=>s?.function_check?.passed??s?.arithmetic_check?.passed;[r.technology+' · '+r.topic,seconds(a),seconds(b),[a,b].map(s=>s?.status!=='ok'?'N/A':passed(s)?'PASS':'FAIL').join(' / ')].forEach(text=>line.append(node('td',text)));adaptive.append(line);}document.getElementById('adaptiveTable').replaceChildren(adaptive);
 const records=project.measurements.results||[],find=policy=>[...records].reverse().find(r=>r.model==='qwen2.5-coder:7b'&&r.options.ssd_policy===policy&&r.metrics.cache==='native-runtime'),normal=find('mapped'),optimized=find('speculative');
 if(normal&&optimized){const rows=['python','logic','english'].map(topic=>({name:({python:'Python',logic:tr('Aritmetica','Arithmetic'),english:tr('Inglese','English')})[topic],normal:normal.metrics.samples.find(s=>s.topic===topic&&s.cache==='warm').tokens_per_second,optimized:optimized.metrics.samples.find(s=>s.topic===topic&&s.cache==='warm').tokens_per_second}));document.getElementById('publicChart').replaceChildren(chart(rows));const table=node('table'),head=node('tr');[tr('Prova','Probe'),'Mapped token/s','Draft token/s',tr('Variazione','Change')].forEach(text=>head.append(node('th',text)));table.append(head);for(const r of rows){const line=node('tr');[r.name,r.normal.toFixed(3),r.optimized.toFixed(3),((r.optimized/r.normal-1)*100).toFixed(1)+'%'].forEach(text=>line.append(node('td',text)));table.append(line);}document.getElementById('benchmarkTable').replaceChildren(table);}
}
document.getElementById('language').onchange=e=>{language=e.target.value;localStorage.setItem('notte.project.language',language);render();};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));for(const id of ['info','news','benchmarks','history'])document.getElementById(id).hidden=id!==button.dataset.view;});
render();fetch('/optimization/data',{credentials:'omit'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(value=>{project=value;render();}).catch(()=>document.getElementById('status').textContent=tr('Dati non disponibili. Riprova più tardi.','Data unavailable. Try again later.'));

let onlineCsrf='',onlineId=null,onlineTimer=null,onlineLast=null;
const onlineEl=id=>document.getElementById(id);
async function onlineApi(path,body){
 const response=await fetch(path,{credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-CSRF-Token':onlineCsrf}:{},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const value=await response.json();if(!response.ok)throw Error(value.error||tr('Accedi come amministratore per provare.','Sign in as administrator to test.'));return value;
}
function onlineGraph(samples,key,title,unit){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 660 112');svg.setAttribute('role','img');svg.setAttribute('aria-label',title);
 const add=(tag,attrs,text)=>{const el=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,String(v));if(text!==undefined)el.textContent=text;svg.append(el);return el;},max=Math.max(1,...samples.map(s=>s.status==='ok'?(s[key]||0):0));add('text',{x:0,y:14,fill:'#e2eadd','font-size':12},title);
 samples.forEach((s,i)=>{const y=30+i*32,value=s.status==='ok'?s[key]:null;add('text',{x:0,y:y+14,fill:'#e2eadd','font-size':12},s.backend==='normal'?'Standard':tr('Ottimizzato','Optimized'));if(typeof value==='number'){add('rect',{x:120,y,width:value/max*385,height:20,rx:3,fill:s.backend==='normal'?'#788275':'#aed087'});add('text',{x:515,y:y+14,fill:'#e2eadd','font-size':12},value.toFixed(2)+' '+unit);}else add('text',{x:120,y:y+14,fill:'#9aa99a','font-size':12},s.status==='error'?tr('Fallito / N/A','Failed / N/A'):'—');});return svg;
}
function onlineRender(run){
 onlineLast=run;const box=onlineEl('onlineResults');box.replaceChildren();const samples=run.result?.samples||run.samples||[],responses=node('div',undefined,'online-responses');
 for(const sample of samples){const card=node('article',undefined,'card');card.append(node('h3',(sample.backend==='normal'?'1. Standard':'2. '+(sample.policy||onlineEl('onlinePolicy').value))+' · '+sample.status),node('pre',sample.content||sample.error||tr('Attendo il primo token…','Waiting for first token…')));if(sample.error&&sample.content)card.append(node('p',sample.error));responses.append(card);}box.append(responses);
 for(const[key,title,unit]of [['first_token_ms',tr('Primo token · più basso = più veloce','First token · lower is faster'),'ms'],['wall_ms',tr('Attesa totale · più basso = più veloce','Total waiting time · lower is faster'),'ms'],['tokens_per_second',tr('Generazione · più alto = più veloce','Decode · higher is faster'),'token/s'],['output_tokens',tr('Token generati','Output tokens'),'token']]){const wrap=node('div',undefined,'chart-box online-chart');wrap.style.overflowX='auto';wrap.append(onlineGraph(samples,key,title,unit));box.append(wrap);}
 if(run.status&&run.status!=='running'){const links=node('div',undefined,'links'),data=node('a',tr('Dati JSON privati','Private JSON data'));data.href='/api/notte/lab/'+run.id+'/export';data.download='notte-lab-'+run.id+'.json';const report=node('button',tr('Report e istogrammi','Report and bar charts'));report.type='button';report.onclick=()=>{
  const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const html='<!doctype html><html><meta charset="utf-8"><title>Notte Test Lab</title><style>body{background:#111c18;color:#e2eadd;font:15px/1.6 sans-serif;max-width:950px;margin:30px auto;padding:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere}svg{max-width:100%}</style><h1>Notte Test Lab #'+run.id+'</h1><p>'+escape(run.result.conditions)+'</p><pre>'+escape(JSON.stringify(run.config,null,2))+'</pre>'+[...box.querySelectorAll('svg')].map(s=>s.outerHTML).join('')+samples.map(s=>'<h2>'+escape(s.backend)+'</h2><pre>'+escape(s.content||s.error||'')+'</pre>').join('');
  const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),link=node('a');link.href=url;link.download='notte-lab-'+run.id+'.html';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 };links.append(data,report);box.append(links);}
}
onlineEl('onlineActivate').onclick=async()=>{try{const me=await onlineApi('/api/me');if(!me.is_admin)throw Error(tr('Test riservato all’amministratore.','Administrator-only test.'));onlineCsrf=me.csrf;const inventory=await onlineApi('/api/notte/models');onlineEl('onlineModel').replaceChildren(...inventory.models.filter(m=>!m.capabilities?.includes('embedding')).map(m=>{const option=node('option',m.name);option.value=m.name;return option;}));if(inventory.models.some(m=>m.name==='notte-coding:latest'))onlineEl('onlineModel').value='notte-coding:latest';onlineEl('onlineForm').hidden=false;onlineEl('onlineActivate').hidden=true;onlineEl('onlineState').textContent=tr('Pronto: standard viene eseguito per primo.','Ready: standard runs first.');}catch(error){onlineEl('onlineState').textContent=error.message;}};
onlineEl('onlineForm').onsubmit=async event=>{event.preventDefault();onlineEl('onlineRun').disabled=true;try{
 const before=await onlineApi('/api/notte/lab'),last=before.runs[0]?.id||0;await onlineApi('/api/notte/lab',{model:onlineEl('onlineModel').value,prompt:onlineEl('onlinePrompt').value,mode:'compare',policy:onlineEl('onlinePolicy').value,context:Number(onlineEl('onlineContext').value),output:Number(onlineEl('onlineOutput').value)});
 onlineId=null;onlineEl('onlineState').textContent=tr('1/2 · Standard in preparazione…','1/2 · Preparing standard…');onlineEl('onlineStop').disabled=false;
 const deadline=Date.now()+900000;const poll=async()=>{try{const value=await onlineApi('/api/notte/lab'),run=value.runs.find(r=>r.id>last&&(!onlineId||r.id===onlineId));if(run){onlineId=run.id;if(value.active?.id===run.id){onlineRender(value.active);onlineEl('onlineState').textContent=value.active.backend==='optimized'?tr('2/2 · Ottimizzazione scelta in corso…','2/2 · Chosen optimization running…'):tr('1/2 · Standard in corso…','1/2 · Standard running…');}else{onlineRender(run);if(run.status!=='running'){onlineEl('onlineState').textContent=tr('Confronto terminato: ','Comparison finished: ')+run.status;onlineEl('onlineRun').disabled=false;onlineEl('onlineStop').disabled=true;return;}}}if(!run){const state=await onlineApi('/api/notte/status');if(!state.running&&state.error)throw Error(state.error);}if(Date.now()>deadline)throw Error(tr('Attesa oltre il limite; il risultato resta nella Test Lab.','Wait limit exceeded; the result remains in Test Lab.'));onlineTimer=setTimeout(poll,1500);}catch(error){onlineEl('onlineState').textContent=error.message;onlineEl('onlineRun').disabled=false;onlineEl('onlineStop').disabled=true;}};await poll();
 }catch(error){onlineEl('onlineState').textContent=error.message;onlineEl('onlineRun').disabled=false;}};
onlineEl('onlineStop').onclick=async()=>{try{const current=await onlineApi('/api/notte/lab');if(onlineId&&current.active?.id===onlineId)await onlineApi('/api/notte/action',{action:'stop'});}catch(error){onlineEl('onlineState').textContent=error.message;}};
function onlineRoute(){if(location.hash==='#test'){document.querySelector('[data-view=benchmarks]').click();onlineEl('onlineLab').scrollIntoView({block:'start'});}}
window.addEventListener('hashchange',onlineRoute);onlineRoute();
