/* Personal handwriting fonts and editable text objects. All assets stay local. */
(()=>{'use strict';
const fontNames={serif:'Georgia,serif',sans:'Arial,sans-serif',mono:'monospace',book:'Tramonto Book,Georgia,serif',classic:'Tramonto Classic,Georgia,serif',humanist:'Tramonto Humanist,Arial,sans-serif',geometric:'Tramonto Geometric,Arial,sans-serif',slab:'Tramonto Slab,Georgia,serif',hand:'Tramonto Hand,cursive',script:'Tramonto Script,cursive',typewriter:'Tramonto Typewriter,monospace',custom:'TramontoPersonal,Georgia,serif'};
function family(name){return fontNames[name]||fontNames.serif;}
function element(tag,id,text){const e=node(tag,text);if(id)e.id=id;return e;}
function action(id,label,fn){const b=element('button',id,label);b.type='button';b.className='secondary-button';b.addEventListener('click',fn);return b;}
function field(host,id,label,type,value){const l=node('label',label),e=element(type==='textarea'?'textarea':'input',id);if(type!=='textarea')e.type=type;e.value=value;l.append(e);host.append(l);return e;}
const customOption=node('option','Il mio font');customOption.value='custom';$('noteFont').append(customOption);
const textTools=element('div','drawingTextTools');textTools.className='drawing-text-tools';
const textValue=field(textTools,'drawingText','Testo','textarea','Il mio testo');textValue.maxLength=1000;
const textSize=field(textTools,'drawingTextSize','Dimensione','number',28);textSize.min=8;textSize.max=160;
const textFont=element('select','drawingTextFont');for(const option of $('noteFont').options)textFont.append(option.cloneNode(true));const fontLabel=node('label','Font');fontLabel.append(textFont);textTools.append(fontLabel);
let selectedText=null,textDrag=null;
function syncText(){if(!doc||!selectedText||!doc.content.drawing.strokes.includes(selectedText))return;drawingHistory.push(clone(doc.content.drawing.strokes));drawingHistory=drawingHistory.slice(-20);selectedText.text=textValue.value;selectedText.text_size=Math.max(8,Math.min(160,Number(textSize.value)||28));selectedText.font=textFont.value;redrawDrawing();changed();}
for(const e of [textValue,textSize,textFont])e.addEventListener('change',syncText);
textTools.append(action('drawingTextApply','Aggiorna testo',syncText),action('drawingTextNew','Nuovo testo',()=>{selectedText=null;$('drawingMessage').textContent='Clicca sul disegno per inserire il testo.';}),action('drawingTextRemove','Elimina testo',()=>{if(!doc||!selectedText)return;drawingHistory.push(clone(doc.content.drawing.strokes));doc.content.drawing.strokes=doc.content.drawing.strokes.filter(s=>s!==selectedText);selectedText=null;redrawDrawing();changed();}));
textTools.append(node('p','Scegli Testo e clicca sul foglio. Clicca un testo per modificarlo; trascinalo per spostarlo. ⌘Z / Ctrl+Z annulla.'));
$('drawingTools').after(textTools);textTools.hidden=true;
$('drawingTool').addEventListener('change',()=>{textTools.hidden=$('drawingTool').value!=='text';selectedText=null;});
const canvas=$('drawingCanvas');
canvas.addEventListener('pointerdown',event=>{if(!doc||erasing||$('drawingTool').value!=='text'||event.button>0)return;event.preventDefault();event.stopImmediatePropagation();const p=canvasPoint(event);selectedText=[...doc.content.drawing.strokes].reverse().find(s=>{if(s.tool!=='text')return false;ctx.font=s.text_size+'px '+family(s.font);return p[0]>=s.points[0][0]-8&&p[0]<=s.points[0][0]+Math.max(...s.text.split('\n').map(t=>ctx.measureText(t).width))+8&&p[1]>=s.points[0][1]-8&&p[1]<=s.points[0][1]+s.text.split('\n').length*s.text_size*1.25+8;});
if(!selectedText){if(!textValue.value.trim()||doc.content.drawing.strokes.length>=500)return;drawingHistory.push(clone(doc.content.drawing.strokes));selectedText={tool:'text',color:$('penColor').value,size:3,text:textValue.value,text_size:Math.max(8,Math.min(160,Number(textSize.value)||28)),font:textFont.value,points:[p]};doc.content.drawing.strokes.push(selectedText);changed();}
else{textValue.value=selectedText.text;textSize.value=selectedText.text_size;textFont.value=selectedText.font;}
textDrag={pointer:event.pointerId,start:p,origin:[...selectedText.points[0]],saved:false};canvas.setPointerCapture(event.pointerId);redrawDrawing();$('drawingMessage').textContent='Testo selezionato: modifica i campi oppure trascinalo.';},true);
canvas.addEventListener('pointermove',event=>{if(!textDrag||!selectedText)return;event.preventDefault();event.stopImmediatePropagation();const p=canvasPoint(event);if(!textDrag.saved&&Math.hypot(p[0]-textDrag.start[0],p[1]-textDrag.start[1])>2){drawingHistory.push(clone(doc.content.drawing.strokes));textDrag.saved=true;}if(textDrag.saved){selectedText.points=[[Math.max(0,Math.min(1000,textDrag.origin[0]+p[0]-textDrag.start[0])),Math.max(0,Math.min(640,textDrag.origin[1]+p[1]-textDrag.start[1]))]];redrawDrawing();}},true);
for(const kind of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(kind,()=>{if(textDrag?.saved)changed();textDrag=null;});

const workshop=element('details','fontWorkshop');workshop.className='font-workshop';workshop.append(node('summary','Crea il tuo font'));
const body=node('div');body.className='font-workshop-body';workshop.append(body);body.append(node('p','Disegna lettere, numeri e simboli nella griglia. I caratteri mancanti usano il font normale. Il font si salva nella pagina e puoi scaricarlo come file OTF.'));
const name=field(body,'customFontName','Nome del font','text','Il mio font');name.maxLength=60;
const alphabet=element('div','customFontAlphabet');alphabet.className='custom-font-alphabet';body.append(alphabet);
const glyphCanvas=element('canvas','customGlyphCanvas');glyphCanvas.width=300;glyphCanvas.height=300;glyphCanvas.tabIndex=0;glyphCanvas.setAttribute('aria-label','Disegna il carattere selezionato');body.append(glyphCanvas);
const glyphLabel=element('p','customGlyphLabel');body.append(glyphLabel);
const weight=field(body,'customFontWeight','Spessore del tratto','range',10);weight.min=2;weight.max=24;
const preview=element('input','customFontPreview');preview.value='Aa Bb Cc 0123 · Il mio font';preview.setAttribute('aria-label','Anteprima del font personale');body.append(preview);
const message=element('p','customFontMessage');message.className='tool-message';message.setAttribute('role','status');body.append(message);
const buttons=node('div');buttons.className='tool-actions';body.append(buttons);
let draft={name:'Il mio font',weight:10,glyphs:{}},char='A',glyphHistory=[],glyphStroke=null,fontFace=null,fontSerial=0;
try{const stored=JSON.parse(localStorage.getItem('alba.customFont'));if(stored?.glyphs&&typeof stored.glyphs==='object')draft=stored;}catch(_){}
function lines(){return draft.glyphs[char]||[];}
function redrawGlyph(){const c=glyphCanvas.getContext('2d');c.clearRect(0,0,300,300);c.fillStyle='#fffdf7';c.fillRect(0,0,300,300);c.strokeStyle='#e2e4db';c.lineWidth=1;for(let n=30;n<300;n+=30){c.beginPath();c.moveTo(n,0);c.lineTo(n,300);c.moveTo(0,n);c.lineTo(300,n);c.stroke();}c.strokeStyle='#879980';c.beginPath();c.moveTo(0,240);c.lineTo(300,240);c.stroke();c.font='220px Georgia';c.fillStyle='#263c3112';c.textAlign='center';c.fillText(char,150,240);c.strokeStyle='#263c31';c.lineWidth=Number(weight.value);c.lineCap='round';c.lineJoin='round';for(const line of lines()){c.beginPath();line.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));if(line.length===1){c.arc(...line[0],Number(weight.value)/2,0,Math.PI*2);c.fillStyle='#263c31';c.fill();}c.stroke();}glyphLabel.textContent='Carattere: '+char+' · linea verde = base della lettera';for(const b of alphabet.children){b.setAttribute('aria-pressed',String(b.textContent===char));b.classList.toggle('has-glyph',!!draft.glyphs[b.textContent]?.length);}}
for(const c of 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789àèéìòùÀÈÉÌÒÙ.,:;!?+-=()[]{}@%/'){alphabet.append(action(null,c,()=>{char=c;glyphHistory=[];redrawGlyph();}));}
const character=field(body,'customFontCharacter','Altro carattere','text','');character.maxLength=2;character.addEventListener('change',()=>{const value=Array.from(character.value)[0];if(value){char=value;glyphHistory=[];redrawGlyph();}});
function persist(){draft.name=name.value.trim()||'Il mio font';draft.weight=Number(weight.value);try{localStorage.setItem('alba.customFont',JSON.stringify(draft));}catch(_){}if(doc){doc.content.custom_font=clone(draft);changed();}redrawGlyph();buildFont().catch(e=>message.textContent=e.message);}
function glyphPoint(e){const b=glyphCanvas.getBoundingClientRect();return [Math.max(0,Math.min(300,Math.round((e.clientX-b.left)*300/b.width))),Math.max(0,Math.min(300,Math.round((e.clientY-b.top)*300/b.height)))];}
glyphCanvas.addEventListener('pointerdown',e=>{if(e.button>0)return;e.preventDefault();glyphCanvas.focus();glyphCanvas.setPointerCapture(e.pointerId);glyphHistory.push(clone(lines()));glyphHistory=glyphHistory.slice(-30);if(!draft.glyphs[char])draft.glyphs[char]=[];if(lines().length>=100)return;glyphStroke=[glyphPoint(e)];draft.glyphs[char].push(glyphStroke);redrawGlyph();});
glyphCanvas.addEventListener('pointermove',e=>{if(!glyphStroke)return;const p=glyphPoint(e),last=glyphStroke.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<3||glyphStroke.length>=1000)return;glyphStroke.push(p);redrawGlyph();});
for(const kind of ['pointerup','pointercancel','lostpointercapture'])glyphCanvas.addEventListener(kind,()=>{if(glyphStroke){glyphStroke=null;persist();}});
function undoGlyph(){if(glyphHistory.length){draft.glyphs[char]=glyphHistory.pop();persist();}}
buttons.append(action('customGlyphUndo','Annulla tratto',undoGlyph),action('customGlyphClear','Pulisci carattere',()=>{glyphHistory.push(clone(lines()));delete draft.glyphs[char];persist();}));
function fontBuffer(){const glyphs=[new opentype.Glyph({name:'.notdef',advanceWidth:650,path:new opentype.Path()}),new opentype.Glyph({name:'space',unicode:32,advanceWidth:320,path:new opentype.Path()})];
for(const [letter,strokes]of Object.entries(draft.glyphs)){if(!strokes.length||letter===' ')continue;const path=new opentype.Path(),r=draft.weight/2,scale=3;const point=(p)=>[p[0]*scale,(240-p[1])*scale];
function circle(p){const [x,y]=point(p),radius=r*scale,k=.55228475*radius;path.moveTo(x+radius,y);path.curveTo(x+radius,y+k,x+k,y+radius,x,y+radius);path.curveTo(x-k,y+radius,x-radius,y+k,x-radius,y);path.curveTo(x-radius,y-k,x-k,y-radius,x,y-radius);path.curveTo(x+k,y-radius,x+radius,y-k,x+radius,y);path.close();}
for(const stroke of strokes){for(let i=0;i<stroke.length;i++){circle(stroke[i]);if(!i)continue;const a=stroke[i-1],b=stroke[i],length=Math.hypot(b[0]-a[0],b[1]-a[1]);if(!length)continue;const dx=(b[0]-a[0])/length*r,dy=(b[1]-a[1])/length*r;const polygon=[[a[0]-dy,a[1]+dx],[a[0]+dy,a[1]-dx],[b[0]+dy,b[1]-dx],[b[0]-dy,b[1]+dx]];polygon.forEach((p,j)=>j?path.lineTo(...point(p)):path.moveTo(...point(p)));path.close();}}
const right=Math.max(...strokes.flat().map(p=>p[0]));glyphs.push(new opentype.Glyph({name:'uni'+letter.codePointAt(0).toString(16),unicode:letter.codePointAt(0),advanceWidth:Math.max(300,(right+20)*scale),path}));}
return new opentype.Font({familyName:draft.name||'Il mio font',styleName:'Regular',unitsPerEm:1000,ascender:800,descender:-200,glyphs}).toArrayBuffer();}
async function buildFont(){const serial=++fontSerial;if(!Object.values(draft.glyphs).some(a=>a.length)){if(fontFace)document.fonts.delete(fontFace);fontFace=null;preview.style.fontFamily='Georgia';return;}const candidate=new FontFace('TramontoPersonal',fontBuffer());await candidate.load();if(serial!==fontSerial)return;if(fontFace)document.fonts.delete(fontFace);fontFace=candidate;document.fonts.add(candidate);preview.style.fontFamily=family('custom');redrawDrawing();window.TramontoLab?.fitPage();}
buttons.append(action('customFontApply','Applica al testo della pagina',async()=>{if(!doc)return;if(!Object.values(draft.glyphs).some(a=>a.length)){message.textContent='Disegna almeno un carattere prima di applicare il font.';return;}persist();await buildFont();doc.content.font='custom';$('noteFont').value='custom';$('noteEditor').dataset.font='custom';textFont.value='custom';changed();message.textContent='Font applicato alla pagina e disponibile per il testo del disegno.';}),action('customFontDownload','Scarica font OTF',()=>{if(!Object.values(draft.glyphs).some(a=>a.length)){message.textContent='Disegna almeno un carattere.';return;}download(new Blob([fontBuffer()],{type:'font/otf'}),(draft.name||'font-personale').replace(/[^\p{L}\p{N} _-]/gu,'')+'.otf');}));
for(const e of [name,weight])e.addEventListener('change',persist);
$('pane-draw').append(workshop);
function load(){selectedText=null;textDrag=null;glyphStroke=null;glyphHistory=[];draft=clone(doc?.content.custom_font||{name:'Il mio font',weight:10,glyphs:{}});if(!doc?.content.custom_font)try{const stored=JSON.parse(localStorage.getItem('alba.customFont'));if(stored?.glyphs)draft=stored;}catch(_){}name.value=draft.name;weight.value=draft.weight;redrawGlyph();buildFont().catch(e=>message.textContent=e.message);}
document.addEventListener('keydown',event=>{if(!(event.metaKey||event.ctrlKey)||event.key.toLowerCase()!=='z'||event.shiftKey)return;const path=event.composedPath();if(path.includes(glyphCanvas)){event.preventDefault();undoGlyph();return;}if(path.some(e=>e instanceof Element&&(e.matches('input,textarea,select,math-field')||e.isContentEditable)))return;const id={draw:'undoDrawing',circuit:'undoCircuit',network:'networkUndo'}[activePane];if(id){event.preventDefault();selectedText=null;textDrag=null;stroke=null;$(id).click();}},true);
window.TramontoFont={load,family};load();
})();
