/* Personal handwriting fonts and editable text objects. All assets stay local. */
(()=>{'use strict';
const fontNames={serif:'Georgia,serif',sans:'Arial,sans-serif',mono:'monospace',book:'Tramonto Book,Georgia,serif',classic:'Tramonto Classic,Georgia,serif',humanist:'Tramonto Humanist,Arial,sans-serif',geometric:'Tramonto Geometric,Arial,sans-serif',slab:'Tramonto Slab,Georgia,serif',hand:'Tramonto Hand,cursive',script:'Tramonto Script,cursive',typewriter:'Tramonto Typewriter,monospace',custom:'TramontoPersonal,Georgia,serif'};
function family(name){return fontNames[name]||fontNames.serif;}
function element(tag,id,text){const e=node(tag,text);if(id)e.id=id;return e;}
function action(id,label,fn){const b=element('button',id,label);b.type='button';b.className='secondary-button';b.addEventListener('click',fn);return b;}
function field(host,id,label,type,value){const l=node('label',label),e=element(type==='textarea'?'textarea':'input',id);if(type!=='textarea')e.type=type;e.value=value;l.append(e);host.append(l);return e;}
const customOption=node('option','Il mio font');customOption.value='custom';$('noteFont').append(customOption);
const textTools=element('div','drawingTextTools');textTools.className='drawing-text-tools';
const textValue=field(textTools,'drawingText','Testo','textarea','Il mio testo');textValue.maxLength=1000;
const textSize=field(textTools,'drawingTextSize','Dimensione','number',28);textSize.min=8;textSize.max=160;
const textFont=element('select','drawingTextFont');for(const option of $('noteFont').options)textFont.append(option.cloneNode(true));const fontLabel=node('label','Font');fontLabel.append(textFont);textTools.append(fontLabel);
let selectedText=null,textDrag=null;
function syncText(){if(!doc||!selectedText||!doc.content.drawing.strokes.includes(selectedText))return;const size=Math.max(8,Math.min(160,Number(textSize.value)||28)),color=$('penColor').value;if(selectedText.text===textValue.value&&selectedText.text_size===size&&selectedText.font===textFont.value&&selectedText.color===color)return;drawingHistory.push(clone(doc.content.drawing.strokes));drawingHistory=drawingHistory.slice(-20);selectedText.text=textValue.value;selectedText.text_size=size;selectedText.font=textFont.value;selectedText.color=color;redrawDrawing();changed();}
for(const e of [textValue,textSize,textFont,$('penColor')])e.addEventListener('change',syncText);
textTools.append(action('drawingTextApply','Aggiorna testo',syncText),action('drawingTextNew','Nuovo testo',()=>{selectedText=null;$('drawingMessage').textContent='Clicca sul disegno per inserire il testo.';}),action('drawingTextRemove','Elimina testo',()=>{if(!doc||!selectedText)return;drawingHistory.push(clone(doc.content.drawing.strokes));doc.content.drawing.strokes=doc.content.drawing.strokes.filter(s=>s!==selectedText);selectedText=null;redrawDrawing();changed();}));
textTools.append(node('p','Scegli Testo e clicca sul foglio. Clicca un testo per modificarlo; trascinalo per spostarlo. ⌘Z / Ctrl+Z annulla.'));
$('drawingTools').after(textTools);textTools.hidden=true;
$('drawingTool').addEventListener('change',()=>{textTools.hidden=$('drawingTool').value!=='text';selectedText=null;});
const canvas=$('drawingCanvas');
canvas.addEventListener('pointerdown',event=>{if(!doc||erasing||$('drawingTool').value!=='text'||event.button>0)return;event.preventDefault();event.stopImmediatePropagation();const p=canvasPoint(event);selectedText=[...doc.content.drawing.strokes].reverse().find(s=>{if(s.tool!=='text')return false;ctx.font=s.text_size+'px '+family(s.font);return p[0]>=s.points[0][0]-8&&p[0]<=s.points[0][0]+Math.max(...s.text.split('\n').map(t=>ctx.measureText(t).width))+8&&p[1]>=s.points[0][1]-8&&p[1]<=s.points[0][1]+s.text.split('\n').length*s.text_size*1.25+8;});
if(!selectedText){if(!textValue.value.trim()||doc.content.drawing.strokes.length>=500)return;drawingHistory.push(clone(doc.content.drawing.strokes));selectedText={tool:'text',color:$('penColor').value,size:3,text:textValue.value,text_size:Math.max(8,Math.min(160,Number(textSize.value)||28)),font:textFont.value,points:[p]};doc.content.drawing.strokes.push(selectedText);changed();}
else{textValue.value=selectedText.text;textSize.value=selectedText.text_size;textFont.value=selectedText.font;$('penColor').value=selectedText.color;}
textDrag={pointer:event.pointerId,start:p,origin:[...selectedText.points[0]],saved:false};canvas.setPointerCapture(event.pointerId);redrawDrawing();$('drawingMessage').textContent='Testo selezionato: modifica i campi oppure trascinalo.';},true);
canvas.addEventListener('pointermove',event=>{if(!textDrag||!selectedText)return;event.preventDefault();event.stopImmediatePropagation();const p=canvasPoint(event);if(!textDrag.saved&&Math.hypot(p[0]-textDrag.start[0],p[1]-textDrag.start[1])>2){drawingHistory.push(clone(doc.content.drawing.strokes));textDrag.saved=true;}if(textDrag.saved){selectedText.points=[[Math.max(0,Math.min(1000,textDrag.origin[0]+p[0]-textDrag.start[0])),Math.max(0,Math.min(640,textDrag.origin[1]+p[1]-textDrag.start[1]))]];redrawDrawing();}},true);
for(const kind of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(kind,()=>{if(textDrag?.saved)changed();textDrag=null;});

const workshop=element('details','fontWorkshop');workshop.className='font-workshop';workshop.append(node('summary','Crea il tuo font'));
const body=node('div');body.className='font-workshop-body';workshop.append(body);body.append(node('p','Crea fino a 10 font personali, anche un carattere alla volta. I preset e i progressi si salvano automaticamente: puoi riprenderli e modificarli più tardi, anche in altre pagine.'));
const presetSelect=element('select','customFontPresets');presetSelect.setAttribute('aria-label','Preset dei font personali');const presetLabel=node('label','I tuoi font');presetLabel.append(presetSelect);body.append(presetLabel);
const presetActions=node('div');presetActions.className='tool-actions';body.append(presetActions);
const presetStatus=element('p','customFontSaveStatus');presetStatus.setAttribute('role','status');body.append(presetStatus);
const name=field(body,'customFontName','Nome del font','text','Il mio font');name.maxLength=60;
const category=element('select','customFontCategory');const MAX_FONT_GLYPHS=512;const groups=[["Maiuscole","ABCDEFGHIJKLMNOPQRSTUVWXYZ"],["Minuscole","abcdefghijklmnopqrstuvwxyz"],["Numeri","0123456789"],["Accenti","àáâãäåāăąæçćčďđèéêëēėęěìíîïīįıłñńňòóôõöøōőœřśšșßťțùúûüūůűųýÿźżžÀÁÂÃÄÅĀĂĄÆÇĆČĎĐÈÉÊËĒĖĘĚÌÍÎÏĪĮİŁÑŃŇÒÓÔÕÖØŌŐŒŘŚŠȘẞŤȚÙÚÛÜŪŮŰŲÝŸŹŻŽ"],["Lettere greche","αβγδεζηθικλμνξοπρσςτυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ"],["Punteggiatura",".,:;!?…·¡¿"],["Virgolette","\"'`«»‹›“”‘’„‚‛‟"],["Simboli comuni","#@&%‰‱§¶†‡*•‣◦~^©®™℠°№ªº"],["Parentesi","()[]{}<>⟨⟩⌈⌉⌊⌋"],["Trattini e barre","-–—―−_/\\|¦‖"],["Valute","$€£¥¢¤₽₹₩₺₴₿"],["Simboli matematici","+−×÷=≠≈≤≥±∞√∑∏∫∂∆∇∈∉⊂⊆∪∩∀∃¬∧∨⇒⇔°²³¹⁰⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉∅∝∴∵∠⊥∥∓∶∼≡≪≫ℕℤℚℝℂ"],["Frecce","←↑→↓↔↕↖↗↘↙⇐⇑⇒⇓⇔⇕⟵⟶⟷↦↩↪"],["Caratteri disegnati",""]];for(const [title]of groups){const o=node('option',title);o.value=title;category.append(o);}const categoryLabel=node('label','Gruppo di caratteri');categoryLabel.append(category);body.append(categoryLabel);
const progress=element('p','customFontProgress');progress.setAttribute('role','status');body.append(progress);
const alphabet=element('div','customFontAlphabet');alphabet.className='custom-font-alphabet';body.append(alphabet);
const glyphCanvas=element('canvas','customGlyphCanvas');glyphCanvas.width=300;glyphCanvas.height=300;glyphCanvas.tabIndex=0;glyphCanvas.setAttribute('aria-label','Disegna il carattere selezionato');body.append(glyphCanvas);
const glyphLabel=element('p','customGlyphLabel');body.append(glyphLabel);
const glyphTools=node('div');glyphTools.className='tool-actions';const glyphPen=action('customGlyphPen','Penna',()=>setGlyphTool(false)),glyphEraser=action('customGlyphEraser','Gomma',()=>setGlyphTool(true));glyphTools.append(glyphPen,glyphEraser);glyphLabel.after(glyphTools);
const eraserSize=field(body,'customGlyphEraserSize','Dimensione gomma','range',24);eraserSize.min=12;eraserSize.max=60;
const weight=field(body,'customFontWeight','Spessore del tratto','range',10);weight.min=2;weight.max=24;
const preview=element('input','customFontPreview');preview.value='Aa Bb Cc 0123 · Il mio font';preview.setAttribute('aria-label','Anteprima del font personale');body.append(preview);
const message=element('p','customFontMessage');message.className='tool-message';message.setAttribute('role','status');body.append(message);
const buttons=node('div');buttons.className='tool-actions';body.append(buttons);
let draft={name:'Il mio font',weight:10,glyphs:{}},char='A',glyphHistory=[],glyphStroke=null,fontFace=null,previewFace=null,fontSerial=0,glyphErasing=false,erasePoint=null;
let presets=[],presetId=null,presetVersion=0,presetDirty=false,presetRevision=0,presetSaving=null,presetTimer=0,presetReady=false,backupKey='',lastPresetId=null;
// Keep the page snapshot linked while a new preset still awaits its server ID.
let linkedDraft=null,linkedSnapshot=null;
function setGlyphTool(erase){glyphErasing=erase;glyphPen.setAttribute('aria-pressed',String(!erase));glyphEraser.setAttribute('aria-pressed',String(erase));glyphCanvas.dataset.tool=erase?'eraser':'pen';eraserSize.parentElement.hidden=!erase;}setGlyphTool(false);
function checkpoint(){if(!backupKey)return;try{localStorage.setItem(backupKey,JSON.stringify({id:presetId,version:presetVersion,font:draft,dirty:presetDirty,activeId:presetId,character:char,category:category.value}));}catch(_){presetStatus.textContent='Copia locale non disponibile. Premi Salva progressi prima di chiudere.';}}
function renderPageFonts(){const select=$('noteFont');for(const option of [...select.options])if(option.value.startsWith('preset:'))option.remove();customOption.textContent=doc?.content.custom_font?.name||'Il mio font';for(const p of presets){const o=node('option',p.font.name);o.value='preset:'+p.id;select.append(o);}select.value=doc?.content.font==='custom'&&presets.some(p=>p.id===doc.content.custom_font?.preset_id)?'preset:'+doc.content.custom_font.preset_id:doc?.content.font||'serif';}
function renderPresets(){presetSelect.replaceChildren();if(!presetId){const o=node('option','Font in lavorazione');o.value='';presetSelect.append(o);}for(const p of presets){const o=node('option',p.id===presetId?draft.name:p.font.name);o.value=p.id;presetSelect.append(o);}presetSelect.value=presetId||'';$('customFontNew').disabled=!presetReady||presets.length>=10;$('customFontDelete').disabled=!presetId;presetSelect.disabled=!presetReady;renderPageFonts();}
async function applyPreset(id){if(!doc)return;const p=presets.find(p=>p.id===id);if(!p)throw Error('Preset non disponibile.');if(!Object.values(p.font.glyphs).some(a=>a.length)){renderPageFonts();throw Error('Disegna almeno un carattere in questo preset.');}doc.content.custom_font={...clone(p.font),preset_id:p.id};doc.content.font='custom';$('noteEditor').dataset.font='custom';textFont.value='custom';renderPageFonts();changed();await buildFont();await saveDoc();}
async function savePreset(){
 clearTimeout(presetTimer);if(!presetReady)return false;if(presetSaving){await presetSaving;return presetDirty?savePreset():true;}if(!presetDirty)return true;
 const stamp=presetRevision,font=clone(draft);delete font.preset_id;presetStatus.textContent='Salvataggio del preset…';
 presetSaving=(async()=>{try{const saved=await api('/api/tramonto/fonts'+(presetId?'/'+presetId:''),presetId?'PUT':'POST',{font,version:presetVersion});presetId=saved.id;presetVersion=saved.version;draft.preset_id=presetId;lastPresetId=presetId;presets=[...presets.filter(p=>p.id!==saved.id),saved];if(presetRevision===stamp)presetDirty=false;checkpoint();renderPresets();presetStatus.textContent=presetDirty?'Modifiche da salvare…':'Preset salvato · '+presets.length+' / 10 font';if(doc?.content.custom_font&&!doc.content.custom_font.preset_id&&((linkedDraft===draft&&linkedSnapshot===doc.content.custom_font)||JSON.stringify(doc.content.custom_font.glyphs)===JSON.stringify(font.glyphs))){doc.content.custom_font.preset_id=presetId;changed();}return true;}catch(e){presetStatus.textContent='Preset non salvato sul server · '+e.message;checkpoint();return false;}})();
 const ok=await presetSaving;presetSaving=null;if(ok&&presetDirty)return savePreset();return ok;
}
function refreshDraft(){name.value=draft.name;weight.value=draft.weight;glyphStroke=null;erasePoint=null;glyphHistory=[];formulaId=null;formulaLines=[];formulaHistory=[];formulaStroke=null;renderAlphabet();renderFormulaList();redrawHandFormula();updateProgress();renderPresets();buildFont().catch(e=>message.textContent=e.message);}
async function selectPreset(id){if(!await savePreset()){presetSelect.value=presetId||'';return;}const p=presets.find(p=>p.id===id);if(!p)return;presetId=p.id;presetVersion=p.version;lastPresetId=p.id;draft={...clone(p.font),preset_id:p.id};char='A';category.value='Maiuscole';checkpoint();refreshDraft();presetStatus.textContent='Preset salvato · '+presets.length+' / 10 font';}
presetSelect.addEventListener('change',()=>selectPreset(presetSelect.value));
presetActions.append(action('customFontSave','Salva progressi',async()=>{persist();await savePreset();await saveDoc();}),action('customFontNew','Nuovo font',async()=>{if(!await savePreset())return;if(presets.length>=10){message.textContent='Hai raggiunto il limite di 10 font.';return;}presetId=null;presetVersion=0;draft={name:'Font '+(presets.length+1),weight:10,glyphs:{}};char='A';category.value='Maiuscole';refreshDraft();persist();await savePreset();}),action('customFontDelete','Elimina preset',async()=>{if(!presetId||!confirm('Eliminare questo preset? Il font già applicato alle pagine resta disponibile nella pagina.'))return;if(!await savePreset())return;try{await api('/api/tramonto/fonts/'+presetId,'DELETE',{version:presetVersion});presets=presets.filter(p=>p.id!==presetId);presetId=null;presetVersion=0;presetDirty=false;draft={name:'Il mio font',weight:10,glyphs:{}};if(presets.length){const p=presets[0];presetId=p.id;presetVersion=p.version;draft={...clone(p.font),preset_id:p.id};}lastPresetId=presetId;checkpoint();refreshDraft();presetStatus.textContent='Preset eliminato · '+presets.length+' / 10 font';}catch(e){message.textContent=e.message;}}));
async function init(userId){backupKey='alba.fontPresets.'+userId;try{presets=(await api('/api/tramonto/fonts')).fonts;presetReady=true;let cached;try{cached=JSON.parse(localStorage.getItem(backupKey));}catch(_){}const p=presets.find(p=>p.id===cached?.activeId)||presets[0];if(cached?.dirty&&cached.font?.glyphs){draft=cached.font;presetId=cached.id;presetVersion=cached.version;presetDirty=true;presetRevision++;presetStatus.textContent='Progressi locali recuperati · premi Salva progressi';}else if(p){draft={...clone(p.font),preset_id:p.id};presetId=p.id;presetVersion=p.version;presetStatus.textContent='Preset salvato · '+presets.length+' / 10 font';}else{try{const old=JSON.parse(localStorage.getItem('alba.customFont'));if(old?.glyphs&&Object.values(old.glyphs).some(a=>a.length))draft=old;}catch(_){}presetStatus.textContent='0 / 10 font · salvataggio automatico';}lastPresetId=presetId;if(groups.some(g=>g[0]===cached?.category))category.value=cached.category;if(typeof cached?.character==='string'&&Array.from(cached.character).length===1)char=cached.character;refreshDraft();}catch(e){presetStatus.textContent='Raccolta font non disponibile · '+e.message;renderPresets();}}
function lines(){return draft.glyphs[char]||[];}
function redrawGlyph(){const c=glyphCanvas.getContext('2d');c.clearRect(0,0,300,300);c.fillStyle='#fffdf7';c.fillRect(0,0,300,300);c.strokeStyle='#e2e4db';c.lineWidth=1;for(let n=30;n<300;n+=30){c.beginPath();c.moveTo(n,0);c.lineTo(n,300);c.moveTo(0,n);c.lineTo(300,n);c.stroke();}c.strokeStyle='#879980';c.beginPath();c.moveTo(0,240);c.lineTo(300,240);c.stroke();c.font='220px Georgia';c.fillStyle='#263c3112';c.textAlign='center';c.fillText(char,150,240);c.strokeStyle='#263c31';c.lineWidth=Number(weight.value);c.lineCap='round';c.lineJoin='round';for(const line of lines()){c.beginPath();line.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));if(line.length===1){c.arc(...line[0],Number(weight.value)/2,0,Math.PI*2);c.fillStyle='#263c31';c.fill();}c.stroke();}glyphLabel.textContent='Carattere: '+char+' · linea verde = base della lettera';for(const b of alphabet.children){b.setAttribute('aria-pressed',String(b.textContent===char));b.classList.toggle('has-glyph',!!draft.glyphs[b.textContent]?.length);}}
function groupCharacters(){return category.value==='Caratteri disegnati'?Object.keys(draft.glyphs).join(''):groups.find(g=>g[0]===category.value)[1];}
function renderAlphabet(){alphabet.replaceChildren();for(const c of new Set(groupCharacters()))alphabet.append(action(null,c,()=>{char=c;glyphHistory=[];checkpoint();redrawGlyph();}));if(!alphabet.children.length)alphabet.append(node('p','Qui trovi tutti i caratteri che hai disegnato, anche quelli inseriti a mano.'));redrawGlyph();}
category.addEventListener('change',()=>{char=Array.from(groupCharacters())[0]||'A';glyphHistory=[];checkpoint();renderAlphabet();});renderAlphabet();
const character=field(body,'customFontCharacter','Altro carattere','text','');character.maxLength=8;character.placeholder='Scrivi o incolla un simbolo';character.autocomplete='off';character.setAttribute('autocapitalize','off');character.spellcheck=false;character.addEventListener('input',()=>{const value=Array.from(character.value.normalize('NFC'))[0];if(value&&!/[\s\p{C}]/u.test(value)){char=value;glyphHistory=[];checkpoint();redrawGlyph();}});
function updateProgress(){if(category.value==='Caratteri disegnati')renderAlphabet();progress.textContent=Object.values(draft.glyphs).filter(a=>a.length).length+' / '+MAX_FONT_GLYPHS+' caratteri disegnati · ogni carattere ha il suo disegno';redrawGlyph();}
function persist(){draft.name=name.value.trim()||'Il mio font';draft.weight=Number(weight.value);presetDirty=true;presetRevision++;checkpoint();renderPresets();presetStatus.textContent='Modifiche da salvare…';clearTimeout(presetTimer);presetTimer=setTimeout(savePreset,500);if(doc&&(!doc.content.custom_font||(presetId&&doc.content.custom_font.preset_id===presetId)||(linkedDraft===draft&&linkedSnapshot===doc.content.custom_font))){linkedDraft=draft;linkedSnapshot=doc.content.custom_font=clone(draft);changed();}updateProgress();buildFont().catch(e=>message.textContent=e.message);}
function glyphPoint(e){const b=glyphCanvas.getBoundingClientRect();return [Math.max(0,Math.min(300,Math.round((e.clientX-b.left)*300/b.width))),Math.max(0,Math.min(300,Math.round((e.clientY-b.top)*300/b.height)))];}
function fontPointCount(){return Object.values(draft.glyphs).flat(2).length+(draft.templates||[]).reduce((n,f)=>n+f.strokes.reduce((k,s)=>k+s.length,0),0);}
function eraseGlyph(point){
 const radius=Number(eraserSize.value)/2+Number(weight.value)/2,out=[];
 for(const line of lines()){
  if(line.length===1){if(Math.hypot(line[0][0]-point[0],line[0][1]-point[1])>radius)out.push(line);continue;}
  let piece=[];const finish=()=>{if(piece.length)out.push(piece);piece=[];};
  for(let i=1;i<line.length;i++){
   const a=line[i-1],b=line[i],dx=b[0]-a[0],dy=b[1]-a[1],x=a[0]-point[0],y=a[1]-point[1],aa=dx*dx+dy*dy,bb=2*(x*dx+y*dy),cc=x*x+y*y-radius*radius,ts=[0,1],disc=bb*bb-4*aa*cc;
   if(aa&&disc>0){for(const t of [(-bb-Math.sqrt(disc))/(2*aa),(-bb+Math.sqrt(disc))/(2*aa)])if(t>0&&t<1)ts.push(t);}ts.sort((a,b)=>a-b);
   for(let j=1;j<ts.length;j++){const lo=ts[j-1],hi=ts[j],mid=(lo+hi)/2;if(Math.hypot(x+dx*mid,y+dy*mid)<=radius){finish();continue;}const from=[a[0]+dx*lo,a[1]+dy*lo],to=[a[0]+dx*hi,a[1]+dy*hi];if(!piece.length)piece.push(from);piece.push(to);}
  }finish();
 }
 if(out.length>100||fontPointCount()-lines().flat().length+out.flat().length>30000){message.textContent='Troppi tratti: usa una gomma più grande o pulisci il carattere.';return;}
 if(out.length)draft.glyphs[char]=out;else delete draft.glyphs[char];
}
glyphCanvas.addEventListener('pointerdown',e=>{if(e.button>0||glyphStroke||erasePoint)return;e.preventDefault();if(!glyphErasing&&((!draft.glyphs[char]&&Object.keys(draft.glyphs).length>=MAX_FONT_GLYPHS)||lines().length>=100||fontPointCount()>=30000)){message.textContent='Limite del font raggiunto: elimina qualche tratto prima di aggiungerne altri.';return;}glyphCanvas.focus();glyphCanvas.setPointerCapture(e.pointerId);glyphHistory.push(clone(lines()));glyphHistory=glyphHistory.slice(-30);if(glyphErasing){erasePoint=glyphPoint(e);eraseGlyph(erasePoint);}else{if(!draft.glyphs[char])draft.glyphs[char]=[];glyphStroke=[glyphPoint(e)];draft.glyphs[char].push(glyphStroke);}presetDirty=true;checkpoint();redrawGlyph();});
glyphCanvas.addEventListener('pointermove',e=>{const p=glyphPoint(e);if(erasePoint){const start=erasePoint,steps=Math.max(1,Math.ceil(Math.hypot(p[0]-start[0],p[1]-start[1])/4));for(let i=1;i<=steps;i++)eraseGlyph([start[0]+(p[0]-start[0])*i/steps,start[1]+(p[1]-start[1])*i/steps]);erasePoint=p;checkpoint();redrawGlyph();return;}if(!glyphStroke)return;const last=glyphStroke.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<3||glyphStroke.length>=1000||fontPointCount()>=30000)return;glyphStroke.push(p);checkpoint();redrawGlyph();});
function finishGlyph(){if(glyphStroke||erasePoint){glyphStroke=null;erasePoint=null;persist();}}
for(const kind of ['pointerup','pointercancel','lostpointercapture'])glyphCanvas.addEventListener(kind,finishGlyph);
function undoGlyph(){if(glyphHistory.length){draft.glyphs[char]=glyphHistory.pop();if(!draft.glyphs[char].length)delete draft.glyphs[char];persist();}}
buttons.append(action('customGlyphUndo','Annulla tratto',undoGlyph),action('customGlyphClear','Pulisci carattere',()=>{glyphHistory.push(clone(lines()));delete draft.glyphs[char];persist();}));
function fontBuffer(value=draft){const glyphs=[new opentype.Glyph({name:'.notdef',advanceWidth:650,path:new opentype.Path()}),new opentype.Glyph({name:'space',unicode:32,advanceWidth:320,path:new opentype.Path()})];
for(const [letter,strokes]of Object.entries(value.glyphs)){if(!strokes.length||letter===' ')continue;const path=new opentype.Path(),r=value.weight/2,scale=4,xs=strokes.flat().map(p=>p[0]),left=Math.min(...xs)-r,right=Math.max(...xs)+r;const point=(p)=>[(p[0]-left+4)*scale,(240-p[1])*scale];
function circle(p){const [x,y]=point(p),radius=r*scale,k=.55228475*radius;path.moveTo(x+radius,y);path.curveTo(x+radius,y+k,x+k,y+radius,x,y+radius);path.curveTo(x-k,y+radius,x-radius,y+k,x-radius,y);path.curveTo(x-radius,y-k,x-k,y-radius,x,y-radius);path.curveTo(x+k,y-radius,x+radius,y-k,x+radius,y);path.close();}
for(const stroke of strokes){for(let i=0;i<stroke.length;i++){circle(stroke[i]);if(!i)continue;const a=stroke[i-1],b=stroke[i],length=Math.hypot(b[0]-a[0],b[1]-a[1]);if(!length)continue;const dx=(b[0]-a[0])/length*r,dy=(b[1]-a[1])/length*r;const polygon=[[a[0]-dy,a[1]+dx],[a[0]+dy,a[1]-dx],[b[0]+dy,b[1]-dx],[b[0]-dy,b[1]+dx]];polygon.forEach((p,j)=>j?path.lineTo(...point(p)):path.moveTo(...point(p)));path.close();}}
glyphs.push(new opentype.Glyph({name:'uni'+letter.codePointAt(0).toString(16),unicode:letter.codePointAt(0),advanceWidth:Math.max(80,(right-left+8)*scale),path}));}
return new opentype.Font({familyName:value.name||'Il mio font',styleName:'Regular',unitsPerEm:1000,ascender:960,descender:-240,glyphs}).toArrayBuffer();}
let fontReady=Promise.resolve();const formulaStyles=new WeakMap();
function styleFormula(target){
 if(!target.isConnected){queueMicrotask(()=>{if(target.isConnected)styleFormula(target);});return;}
 const glyphs=doc?.content.font==='custom'&&fontFace?doc.content.custom_font?.glyphs||{}:{};
 for(const span of target.querySelectorAll('.katex-html span')){
  if(span.children.length||!span.textContent.trim())continue;
  const previous=formulaStyles.get(span);if(previous){span.style.fontFamily=previous.family;span.style.fontStyle=previous.style;span.style.fontWeight=previous.weight;}
  const chars=Array.from(span.textContent);if(!chars.some(c=>glyphs[c]?.length))continue;
  if(!previous)formulaStyles.set(span,{family:span.style.fontFamily,style:span.style.fontStyle,weight:span.style.fontWeight});
  const fallback=getComputedStyle(span).fontFamily;span.style.fontFamily='TramontoPersonal,'+fallback;
  if(chars.every(c=>/\s/u.test(c)||glyphs[c]?.length)){span.style.fontStyle='normal';span.style.fontWeight='normal';}
 }
}
function refreshFormulas(){for(const target of document.querySelectorAll('#formulaPreview, #formulaList .formula-card'))styleFormula(target);}
function embedSvgFont(svg){if(doc?.content.font!=='custom'||!fontFace)return;const bytes=new Uint8Array(fontBuffer(doc.content.custom_font));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='@font-face{font-family:TramontoPersonal;src:url(data:font/otf;base64,'+btoa(binary)+') format("opentype");}';svg.prepend(style);}
$('noteFont').addEventListener('change',refreshFormulas);
function buildFont(){fontReady=buildFontFaces();return fontReady;}
async function buildFontFaces(){const serial=++fontSerial;
 async function face(value,familyName){if(!value||!Object.values(value.glyphs).some(a=>a.length))return null;const unicodeRange=['U+20',...Object.entries(value.glyphs).filter(([,a])=>a.length).map(([c])=>'U+'+c.codePointAt(0).toString(16))].join(',');const candidate=new FontFace(familyName,fontBuffer(value),{unicodeRange});await candidate.load();return candidate;}
 const [candidate,applied]=await Promise.all([face(draft,'TramontoFontPreview'),face(doc?.content.custom_font,'TramontoPersonal')]);if(serial!==fontSerial)return;
 if(previewFace)document.fonts.delete(previewFace);if(fontFace)document.fonts.delete(fontFace);previewFace=candidate;fontFace=applied;if(candidate)document.fonts.add(candidate);if(applied)document.fonts.add(applied);preview.style.fontFamily=candidate?'TramontoFontPreview,Georgia,serif':'Georgia';refreshFormulas();document.dispatchEvent(new Event('tramonto:font-ready'));redrawDrawing();window.TramontoLab?.fitPage();}
buttons.append(action('customFontApply','Applica al testo della pagina',async()=>{if(!doc)return;if(!Object.values(draft.glyphs).some(a=>a.length)){message.textContent='Disegna almeno un carattere prima di applicare il font.';return;}persist();if(!await savePreset())return;doc.content.custom_font=clone(draft);await buildFont();doc.content.font='custom';$('noteFont').value='custom';$('noteEditor').dataset.font='custom';textFont.value='custom';refreshFormulas();document.dispatchEvent(new Event('tramonto:font-ready'));changed();message.textContent='Font applicato al testo, alle formule e al disegno. I simboli non disegnati usano il carattere standard.';}),action('customFontDownload','Scarica font OTF',()=>{if(!Object.values(draft.glyphs).some(a=>a.length)){message.textContent='Disegna almeno un carattere.';return;}download(new Blob([fontBuffer()],{type:'font/otf'}),(draft.name||'font-personale').replace(/[^\p{L}\p{N} _-]/gu,'')+'.otf');}));
for(const e of [name,weight])e.addEventListener('input',persist);
const applyFormulaWriting=action('formulaApplyHandwriting','Applica scrittura alle formule già inserite',async()=>{
 if(!doc)return;if(doc.content.font!=='custom'){formulaStatus.textContent='Scegli il tuo font nel campo Carattere della pagina, poi riprova.';return;}
 const current=doc,images=[...$('richEditor').querySelectorAll('img[data-latex]')];if(!images.length){formulaStatus.textContent='Le nuove formule useranno già la tua scrittura. Non ci sono formule inserite da aggiornare.';return;}
 applyFormulaWriting.disabled=true;const host=node('div');host.id='handwritingFormulaSnapshot';host.style.cssText='position:absolute;left:-10000px;top:0';document.body.append(host);let completed=0;
 try{await fontReady;for(const image of images){if(doc!==current)break;latex(host,image.dataset.latex);if(!await TramontoLab.snapshot(host.id,{latex:image.dataset.latex,replace:image}))break;completed++;}if(doc===current){await saveDoc();document.querySelector('[data-pane=math]').click();window.TramontoStudy?.openTool('formulas');formulaStatus.textContent=completed+' / '+images.length+' formule aggiornate con la tua scrittura.';}}
 catch(e){formulaStatus.textContent=e.message;}finally{host.remove();applyFormulaWriting.disabled=false;}
});$('addFormula').after(applyFormulaWriting);
const formulaWorkshop=element('section','handFormulaWorkshop');formulaWorkshop.className='hand-formula-workshop';formulaWorkshop.append(node('h3','Formule e simboli disegnati'),node('p','Per una formula intera, disegna qui e salvala con un nome. Potrai riutilizzarla nel testo del quaderno e nel foglio di disegno.'));
const formulaName=field(formulaWorkshop,'handFormulaName','Nome della formula','text','La mia formula');formulaName.maxLength=60;
const formulaSelect=element('select','handFormulaSelect');formulaSelect.setAttribute('aria-label','Formule disegnate salvate');formulaWorkshop.append(formulaSelect);
const formulaCanvas=element('canvas','handFormulaCanvas');formulaCanvas.width=600;formulaCanvas.height=220;formulaCanvas.tabIndex=0;formulaCanvas.setAttribute('aria-label','Disegna una formula o un simbolo');formulaWorkshop.append(formulaCanvas);
const formulaSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');formulaSvg.id='handFormulaSvg';formulaSvg.setAttribute('viewBox','0 0 600 220');formulaSvg.hidden=true;formulaWorkshop.append(formulaSvg);
let formulaLines=[],formulaHistory=[],formulaStroke=null,formulaId=null;
function redrawHandFormula(){const c=formulaCanvas.getContext('2d');c.clearRect(0,0,600,220);c.fillStyle='#fffdf7';c.fillRect(0,0,600,220);c.strokeStyle='#e2e4db';c.lineWidth=1;for(let y=20;y<220;y+=20){c.beginPath();c.moveTo(0,y);c.lineTo(600,y);c.stroke();}c.strokeStyle='#263c31';c.lineWidth=Number(weight.value);c.lineCap='round';c.lineJoin='round';formulaSvg.replaceChildren();for(const line of formulaLines){c.beginPath();line.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));if(line.length===1){c.arc(...line[0],c.lineWidth/2,0,Math.PI*2);c.fillStyle='#263c31';c.fill();}c.stroke();const shape=document.createElementNS(formulaSvg.namespaceURI,line.length===1?'circle':'path');if(line.length===1){shape.setAttribute('cx',line[0][0]);shape.setAttribute('cy',line[0][1]);shape.setAttribute('r',Number(weight.value)/2);shape.setAttribute('fill','#263c31');}else{shape.setAttribute('d',line.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' '));shape.setAttribute('stroke','#263c31');shape.setAttribute('fill','none');shape.setAttribute('stroke-width',weight.value);shape.setAttribute('stroke-linecap','round');shape.setAttribute('stroke-linejoin','round');}formulaSvg.append(shape);}}
function formulaPoint(e){const b=formulaCanvas.getBoundingClientRect();return [Math.max(0,Math.min(600,Math.round((e.clientX-b.left)*600/b.width))),Math.max(0,Math.min(220,Math.round((e.clientY-b.top)*220/b.height)))];}
formulaCanvas.addEventListener('pointerdown',e=>{if(e.button>0||formulaLines.length>=100)return;e.preventDefault();formulaCanvas.focus();formulaCanvas.setPointerCapture(e.pointerId);formulaHistory.push(clone(formulaLines));formulaHistory=formulaHistory.slice(-30);formulaStroke=[formulaPoint(e)];formulaLines.push(formulaStroke);redrawHandFormula();});
formulaCanvas.addEventListener('pointermove',e=>{if(!formulaStroke||formulaStroke.length>=1000)return;const p=formulaPoint(e),last=formulaStroke.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<3)return;formulaStroke.push(p);redrawHandFormula();});
for(const kind of ['pointerup','pointercancel','lostpointercapture'])formulaCanvas.addEventListener(kind,()=>{formulaStroke=null;});
function undoFormula(){if(formulaHistory.length){formulaLines=formulaHistory.pop();redrawHandFormula();}}
function renderFormulaList(){formulaSelect.replaceChildren();const empty=node('option','Nuova formula');empty.value='';formulaSelect.append(empty);for(const f of draft.templates||[]){const o=node('option',f.name);o.value=f.id;formulaSelect.append(o);}formulaSelect.value=formulaId||'';}
formulaSelect.addEventListener('change',()=>{const f=draft.templates?.find(f=>f.id===formulaSelect.value);formulaId=f?.id||null;formulaName.value=f?.name||'La mia formula';formulaLines=clone(f?.strokes||[]);formulaHistory=[];redrawHandFormula();});
function saveFormula(){if(!formulaLines.length){message.textContent='Disegna prima una formula.';return false;}const templates=draft.templates||[],existing=templates.find(f=>f.id===formulaId);if(!existing&&templates.length>=20){message.textContent='Puoi salvare fino a 20 formule per pagina.';return false;}const id=formulaId||crypto.randomUUID(),entry={id,name:formulaName.value.trim()||'La mia formula',strokes:clone(formulaLines)};const count=Object.values(draft.glyphs).flat(2).length+templates.filter(f=>f.id!==id).reduce((n,f)=>n+f.strokes.reduce((k,s)=>k+s.length,0),0)+formulaLines.reduce((n,s)=>n+s.length,0);if(count>30000){message.textContent='La raccolta è troppo dettagliata: elimina qualche tratto.';return false;}draft.templates=[...templates.filter(f=>f.id!==id),entry];formulaId=id;persist();renderFormulaList();message.textContent='Formula salvata: '+entry.name;return true;}
const formulaActions=node('div');formulaActions.className='tool-actions';formulaActions.append(action('handFormulaUndo','Annulla tratto',undoFormula),action('handFormulaClear','Pulisci',()=>{formulaHistory.push(clone(formulaLines));formulaLines=[];redrawHandFormula();}),action('handFormulaSave','Salva formula',saveFormula),action('handFormulaNew','Nuova formula',()=>{formulaId=null;formulaLines=[];formulaHistory=[];formulaName.value='La mia formula';renderFormulaList();redrawHandFormula();}),action('handFormulaDelete','Elimina formula salvata',()=>{if(!formulaId)return;draft.templates=(draft.templates||[]).filter(f=>f.id!==formulaId);formulaId=null;formulaLines=[];formulaHistory=[];persist();renderFormulaList();redrawHandFormula();}),action('handFormulaInsertText','Inserisci nel quaderno',async()=>{if(saveFormula()){redrawHandFormula();await TramontoLab.snapshot('handFormulaSvg');}}),action('handFormulaInsertDrawing','Inserisci nel disegno',()=>{if(!doc||!saveFormula())return;const strokes=doc.content.drawing.strokes;if(strokes.length+formulaLines.length>500||strokes.reduce((n,s)=>n+s.points.length,0)+formulaLines.reduce((n,s)=>n+s.length,0)>50000){message.textContent='Il disegno è troppo dettagliato: usa un’altra pagina.';return;}drawingHistory.push(clone(strokes));for(const line of formulaLines)strokes.push({tool:'pen',color:$('penColor').value,size:Number(weight.value),points:line.map(([x,y])=>[100+x,100+y])});changed();redrawDrawing();canvas.scrollIntoView({block:'center'});}));formulaWorkshop.append(formulaActions);body.append(formulaWorkshop);
weight.addEventListener('change',redrawHandFormula);
$('pane-draw').append(workshop);
function load(){selectedText=null;textDrag=null;finishGlyph();glyphHistory=[];
 if(!presetId&&!presetDirty){const previous=doc?.content.custom_font;if(previous){const linked=presets.find(p=>p.id===previous.preset_id);if(linked){presetId=linked.id;presetVersion=linked.version;draft={...clone(linked.font),preset_id:linked.id};}else{draft=clone(previous);delete draft.preset_id;if(presetReady&&Object.values(draft.glyphs).some(a=>a.length))persist();}}else if(presetReady&&Object.values(draft.glyphs).some(a=>a.length))persist();}
 name.value=draft.name;weight.value=draft.weight;updateProgress();renderPresets();formulaId=null;formulaLines=[];formulaHistory=[];formulaStroke=null;renderFormulaList();redrawHandFormula();buildFont().catch(e=>message.textContent=e.message);}
window.addEventListener('online',()=>{if(presetDirty)savePreset();});
window.addEventListener('beforeunload',event=>{finishGlyph();checkpoint();if(presetDirty||presetSaving){event.preventDefault();event.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){finishGlyph();checkpoint();if(presetDirty)savePreset();}});
document.addEventListener('portal:before-navigate',event=>event.detail.waitUntil(savePreset()));
document.addEventListener('keydown',event=>{if(!(event.metaKey||event.ctrlKey)||event.key.toLowerCase()!=='z'||event.shiftKey)return;const path=event.composedPath();if(path.includes(glyphCanvas)){event.preventDefault();undoGlyph();return;}if(path.includes(formulaCanvas)){event.preventDefault();undoFormula();return;}if(path.some(e=>e instanceof Element&&(e.matches('input,textarea,select,math-field')||e.isContentEditable)))return;const id={draw:'undoDrawing',circuit:'undoCircuit',network:'networkUndo'}[activePane];if(id){event.preventDefault();selectedText=null;textDrag=null;stroke=null;$(id).click();}},true);
window.TramontoFont={load,family,init,save:savePreset,apply:applyPreset,styleFormula,embedSvgFont,ready:()=>fontReady,printFace:async(value,name)=>{if(!value||!Object.values(value.glyphs||{}).some(s=>s.length))return null;const unicodeRange=['U+20',...Object.entries(value.glyphs).filter(([,s])=>s.length).map(([c])=>'U+'+c.codePointAt(0).toString(16))].join(',');const face=new FontFace(name,fontBuffer(value),{unicodeRange});await face.load();document.fonts.add(face);return face;}};load();
})();
