/* Study controls use the same checked expression as the plotted curve. */
(()=>{'use strict';
const M=TramontoMath,graph=$('plotSvg'),section=graph.closest('.math-section');let last=null,timer=0;
function button(id,label,action){const b=node('button',label);b.id=id;b.type='button';b.className='secondary-button';b.addEventListener('click',action);return b;}
function numeric(host,id,label,value){const wrap=node('label',label),field=node('input');field.id=id;field.type='number';field.step='any';field.min=-10000;field.max=10000;field.value=value;wrap.append(field);host.append(wrap);return field;}
const formulaGraph=button('formulaToGraph','Inserisci questa formula nel grafico',()=>setExpression($('formulaInput').value));$('cancelFormulaEdit').after(formulaGraph);
const calcGraph=button('calculusToGraph','Inserisci f(x) nel grafico',()=>setExpression($('calcExpression').value));$('calculateRoot').after(calcGraph);
const newFunction=node('div');newFunction.className='tool-actions';const input=node('input');input.id='graphNewExpression';input.placeholder='y = √(x−3) / √(x²−1), oppure LaTeX';input.maxLength=4000;input.setAttribute('aria-label','Nuova funzione del grafico');newFunction.append(input,button('graphAddExpression','+ Aggiungi curva',()=>setExpression(input.value,true)));$('plotExpressions').before(newFunction);
const controls=node('div');controls.className='tool-actions graph-study-controls';const fit=button('graphFitY','Adatta assi y',fitY);controls.append(fit);
const derivative=node('input');derivative.id='graphDerivative';derivative.type='checkbox';const derivativeLabel=node('label','Mostra derivata');derivativeLabel.prepend(derivative);controls.append(derivativeLabel);
const shade=node('input');shade.id='graphShadeArea';shade.type='checkbox';const shadeLabel=node('label','Evidenzia area');shadeLabel.prepend(shade);controls.append(shadeLabel);
const areaA=numeric(controls,'graphAreaFrom','Da x =',0),areaB=numeric(controls,'graphAreaTo','a x =',1);
controls.append(button('graphAreaVisible','Usa tratto visibile',()=>{try{const settings=graphSettings(),fn=expressionFunction(settings.expressions[0]),a=M.analyze(settings.expressions[0],fn);const interval=a.intervals.find(s=>s.hi>settings.x_min&&s.lo<settings.x_max);if(!interval)throw Error('Non ci sono tratti del dominio nell’intervallo visibile.');const lo=Math.max(settings.x_min,interval.lo),hi=Math.min(settings.x_max,interval.hi),eps=(hi-lo)/1000;areaA.value=lo+(lo===interval.lo&&!interval.lc?eps:0);areaB.value=hi-(hi===interval.hi&&!interval.hc?eps:0);plot(true);}catch(e){$('graphMessage').textContent=e.message;}}));graph.before(controls);
const actions=$('plotGraph').parentElement;const insertGraph=button('insertGraphNotebook','Inserisci grafico nel quaderno',async()=>{insertGraph.disabled=true;try{await TramontoLab.snapshot('plotSvg');}finally{insertGraph.disabled=false;}});actions.append(insertGraph);
actions.append(button('studyFunction','Studia funzione',()=>{if(!plot(true))try{const settings=graphSettings(),functions=settings.expressions.map(expressionFunction);renderStudy(settings,functions);}catch(e){$('graphMessage').textContent=e.message;}}));
const report=node('section');report.id='functionStudy';report.className='function-study';report.setAttribute('aria-label','Studio della prima funzione');section.append(report);
const reportActions=node('div');reportActions.className='tool-actions';reportActions.append(button('insertFunctionStudy','Inserisci studio nel quaderno',()=>{if(!plot(false)||!last)return;TramontoLab.insertHtml(notebookReport());}));section.append(reportActions);
const note=node('p','Dominio: condizioni reali e intervalli per vincoli polinomiali fino al secondo grado. Le condizioni non risolte restano esplicite. Zeri e segno delle altre funzioni, quadranti e aree sono stime nell’intervallo visibile. Integrali numerici: scegli un tratto continuo del dominio.');note.className='tool-note';section.append(note);
const examples=node('div');examples.className='graph-examples';for(const [name,value]of [['Il tuo esempio','sqrt(x-3)/sqrt(x^2-1)'],['Parabola','x^2-4'],['Frazione','(x+1)/(x-2)'],['Logaritmo','log(x)'],['Seno','sin(x)'],['Valore assoluto','abs(x-2)']])examples.append(button('',name,()=>setExpression(value)));newFunction.after(examples);
function options(){const from=Number(areaA.value),to=Number(areaB.value);if(!Number.isFinite(from)||!Number.isFinite(to)||from>=to||Math.abs(from)>10000||Math.abs(to)>10000)throw Error('Per l’area scegli estremi finiti a < b tra −10000 e 10000.');return {show_area:shade.checked,show_derivative:derivative.checked,area_from:from,area_to:to};}
function setExpression(value,append=false){try{const expression=M.normalize(value);expressionFunction(expression);const values=append?$('plotExpressions').value.split('\n').map(x=>x.trim()).filter(Boolean):[];if(values.length>=3)throw Error('Puoi tracciare al massimo tre curve.');values.push(expression);$('plotExpressions').value=values.join('\n');document.querySelector('[data-pane=math]').click();fitY();graph.scrollIntoView({block:'center'});}catch(e){$('graphMessage').textContent=e.message;}}
function fitY(){try{const settings=graphSettings(),values=[];for(const expression of settings.expressions){const fn=expressionFunction(expression);for(let i=0;i<=600;i++){const y=fn(settings.x_min+(settings.x_max-settings.x_min)*i/600);if(Number.isFinite(y)&&Math.abs(y)<1e8)values.push(y);}}if(!values.length){plot(false);return;}values.sort((a,b)=>a-b);const lo=Math.min(0,values[Math.floor(values.length*.02)]),hi=Math.max(0,values[Math.floor((values.length-1)*.98)]),padding=Math.max(.2,(hi-lo)*.12);$('yMin').value=Math.max(-10000,Math.floor((lo-padding)*100)/100);$('yMax').value=Math.min(10000,Math.ceil((hi+padding)*100)/100);if(Number($('yMin').value)>=Number($('yMax').value))throw Error('I valori sono troppo grandi: cambia l’intervallo di x.');plot(true);}catch(e){$('graphMessage').textContent=e.message;}}
function drawArea(settings,functions,svg,px,py){const opts=options();if(!opts.show_area)return;const fn=functions[0];let points=[];function finish(){if(points.length>1){const path='M'+px(points[0][0])+' '+py(0)+points.map(([x,y])=>' L'+px(x)+' '+py(y)).join('')+' L'+px(points.at(-1)[0])+' '+py(0)+' Z';svg.append(svgNode('path',{d:path,fill:'#d58c5745',stroke:'none','clip-path':'url(#plotClip)','data-shaded-area':'true'}));}points=[];}
 const a=Math.max(settings.x_min,opts.area_from),b=Math.min(settings.x_max,opts.area_to);if(a>=b)return;for(let i=0;i<=500;i++){const x=a+(b-a)*i/500,y=fn(x);if(!Number.isFinite(y)||Math.abs(py(y))>1e6){finish();continue;}if(points.length&&Math.abs(py(y)-py(points.at(-1)[1]))>340)finish();points.push([x,y]);}finish();}
function onPlot(settings,functions,svg,px,py){renderStudy(settings,functions);if(!derivative.checked||!last)return;try{const fn=expressionFunction(last.analysis.derivative);let path='',previous=null;for(let i=0;i<=600;i++){const x=settings.x_min+(settings.x_max-settings.x_min)*i/600,y=fn(x),p=py(y);if(!last.analysis.allowed(x)||!Number.isFinite(y)||Math.abs(p)>1e6){previous=null;continue;}path+=(previous!==null&&Math.abs(p-previous)<280?' L':' M')+px(x).toFixed(2)+' '+p.toFixed(2);previous=p;}svg.append(svgNode('path',{d:path,stroke:'#3159a4','stroke-width':1.6,'stroke-dasharray':'6 4',fill:'none','clip-path':'url(#plotClip)','data-derivative':'true'}));svg.append(svgNode('text',{x:735,y:15,'text-anchor':'end',fill:'#3159a4','font-size':11},'f′(x)'));}catch(_){$('graphMessage').textContent+=' · Derivata disponibile nel riepilogo; non tracciabile con questi comandi.';}}
function addCard(host,title,value,id){const card=node('div');card.className='study-card';card.append(node('h4',title));const text=node('p',value);if(id)text.id=id;card.append(text);host.append(card);return card;}
function table(headers,rows){const t=node('table');t.className='lab-table';const head=node('tr');headers.forEach(h=>head.append(node('th',h)));t.append(head);for(const row of rows){const tr=node('tr');row.forEach(x=>tr.append(node('td',String(x))));t.append(tr);}return t;}
function renderStudy(settings,functions){const expression=settings.expressions[0],fn=functions[0],analysis=M.study(expression,fn,settings.x_min,settings.x_max);let area=null,areaError='';const opts=options();try{area=M.integrate(fn,opts.area_from,opts.area_to,analysis.allowed);}catch(e){areaError=e.message;}
 last={expression,settings,analysis,area,areaError,options:opts};report.replaceChildren(node('h3','Studio di f(x) = '+expression));const cards=node('div');cards.className='study-cards';report.append(cards);
 addCard(cards,'Dominio reale',analysis.domain,'studyDomain');addCard(cards,'Zeri',analysis.zero.zero?'Tutto il dominio':analysis.zeros.length?analysis.zeros.map(M.format).join(' · '):analysis.exact?'Nessuno':'Nessuno rilevato nei campioni','studyZeros');addCard(cards,'Intersezione con l’asse y',analysis.yIntercept===null?'x = 0 fuori dal dominio':'(0; '+M.format(analysis.yIntercept)+')','studyYIntercept');
 const quadrants=addCard(cards,'Quadranti occupati nel tratto visibile',analysis.quadrants.join(' · ')||'Solo assi o nessun punto reale','studyQuadrants');const diagram=svgNode('svg',{viewBox:'0 0 120 120',class:'quadrants-diagram',role:'img','aria-label':'Quadranti occupati: '+analysis.quadrants.join(', ')});for(const [name,x,y]of [['I',60,0],['II',0,0],['III',0,60],['IV',60,60]]){diagram.append(svgNode('rect',{x,y,width:60,height:60,fill:analysis.quadrants.includes(name)?'#456b4340':'#87998010'}));diagram.append(svgNode('text',{x:x+30,y:y+34,'text-anchor':'middle',fill:'#263c31','font-size':14},name));}diagram.append(svgNode('path',{d:'M60 0V120M0 60H120',stroke:'#879980'}));quadrants.append(diagram);
 addCard(cards,'Area tra a e b',area?'Area geometrica ≈ '+M.format(area.absolute)+' · integrale con segno ≈ '+M.format(area.signed):areaError,'studyArea');
 report.append(node('h4',analysis.exact?'Studio del segno':'Segno stimato nel tratto visibile'));report.append(table(['Intervallo','f(x)'],analysis.signs.map(s=>['('+M.format(s.lo)+'; '+M.format(s.hi)+')',s.sign])));report.append(node('p','Nei punti elencati tra gli zeri, f(x) = 0. I punti fuori dal dominio sono esclusi.'));
 report.append(node('h4','Derivata simbolica'),node('pre',analysis.derivative));report.append(node('h4','Tabella di valori'));const values=Array.from({length:7},(_,i)=>{const x=settings.x_min+(settings.x_max-settings.x_min)*i/6,y=fn(x);return [M.format(x),Number.isFinite(y)&&analysis.allowed(x)?M.format(y):'fuori dominio'];});report.append(table(['x','f(x)'],values));
}
function notebookReport(){const host=node('div');host.append(node('h3','Studio di f(x) = '+last.expression),node('p','Dominio reale: '+last.analysis.domain),node('p','Zeri: '+(last.analysis.zero.zero?'tutto il dominio':last.analysis.zeros.map(M.format).join(', ')||'nessuno rilevato')),node('p','Quadranti nel tratto visibile: '+(last.analysis.quadrants.join(', ')||'solo assi')),node('p','Derivata: '+last.analysis.derivative));host.append(table(['Intervallo',last.analysis.exact?'Segno':'Segno stimato'],last.analysis.signs.map(s=>['('+M.format(s.lo)+'; '+M.format(s.hi)+')',s.sign])));if(last.area)host.append(node('p','Da '+M.format(last.options.area_from)+' a '+M.format(last.options.area_to)+': area geometrica ≈ '+M.format(last.area.absolute)+'; integrale ≈ '+M.format(last.area.signed)+'.'));host.append(node('p',last.analysis.exact?'Quadranti e integrali sono stime numeriche nel tratto visibile.':'Zeri, segno, quadranti e integrali sono stime numeriche nel tratto visibile.'),node('p'));return host.innerHTML;}
for(const e of [derivative,shade,areaA,areaB])e.addEventListener('change',()=>plot(true));
for(const e of [$('plotExpressions'),$('xMin'),$('xMax'),$('yMin'),$('yMax')])e.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>plot(false),450);});
function load(){clearTimeout(timer);last=null;report.replaceChildren();const saved=doc?.content.graph.study;shade.checked=saved?.show_area||false;derivative.checked=saved?.show_derivative||false;areaA.value=saved?.area_from??0;areaB.value=saved?.area_to??1;if(doc&&activePane==='math')plot(false);}
TramontoLab.insertHtml=html=>{document.querySelector('[data-pane=text]').click();TramontoLab.insertReportHtml(html);};
function clear(){last=null;report.replaceChildren();}
window.TramontoStudy={options,onPlot,drawArea,load,setExpression,fitY,clear};load();
})();
