/* Tramonto: fixed A4 pages and local teaching laboratories. No external scripts. */
(()=>{'use strict';
const insert=(target,html)=>{const template=document.createElement('template');template.innerHTML=html;$(target).appendChild(template.content);};
const button=(text,action)=>{const b=node('button',text);b.type='button';b.className='secondary-button';b.addEventListener('click',action);return b;};
let restoring=false,positionTimer=0,paginationTimer=0,paginating=false,job=null,pollTimer=0,netMode='select',netType='pc',netSelected=null,netStart=null,netDrag=null,netHistory=[];
function storePosition(keepalive=false){if(!doc||restoring||!csrf)return;fetch('/api/tramonto/workspace',{method:'POST',credentials:'same-origin',keepalive,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({notebook_id:doc.notebook_id,note_id:doc.id,scroll_y:Math.round(window.scrollY)})}).catch(()=>{});}
function restorePosition(y){restoring=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{window.scrollTo(0,Number(y)||0);setTimeout(()=>{restoring=false;storePosition();},400);}));}
window.addEventListener('scroll',()=>{clearTimeout(positionTimer);positionTimer=setTimeout(storePosition,700);},{passive:true});
window.addEventListener('pagehide',()=>storePosition(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)storePosition(true);});
function fitPage(){const sheet=$('a4Sheet'),frame=$('a4Frame');if(!sheet||!frame||!frame.clientWidth)return;const scale=Math.min(1,frame.clientWidth/794);sheet.style.transform='scale('+scale+')';frame.style.height=(1123*scale)+'px';
 const editor=$('richEditor'),style=getComputedStyle(editor),probe=node('div'),marker=node('span');probe.style.cssText='position:absolute;left:-10000px;top:0;white-space:nowrap;padding:0;margin:0;line-height:28px;font:'+style.font;probe.style.lineHeight='28px';marker.style.cssText='display:inline-block;width:0;height:0;padding:0;margin:0';probe.append('Abg',marker);document.body.appendChild(probe);const baseline=marker.getBoundingClientRect().top-probe.getBoundingClientRect().top;probe.remove();editor.style.setProperty('--rule-offset',(baseline-28)+'px');}
new ResizeObserver(fitPage).observe($('a4Frame'));
function openNote(){ $('bookCollection').hidden=true;$('pageNumber').textContent='Pagina '+doc.page_number+' · A4';$('sheetNumber').textContent=doc.page_number;netSelected=null;netStart=null;netHistory=[];renderNetwork();fitPage();storePosition();$('pageHint').textContent=$('richEditor').scrollHeight>$('richEditor').clientHeight+2?'Questa pagina contiene testo lungo: usa «Distribuisci testo su A4» per numerarlo su più pagine.':'Formato A4 · il testo che supera la pagina continua su una nuova pagina.';}
async function navigatePage(direction){if(!doc||!await saveDoc())return;const list=(await api('/api/tramonto/notes?notebook='+bookId)).notes,index=list.findIndex(n=>n.id===doc.id),target=list[index+direction];if(target)await windowOpen(target.id);else if(direction>0)await newNote();}
async function windowOpen(id){$('bookCollection').hidden=true;await openNoteParent(id);}
const openNoteParent=globalThis.TramontoOpenNote||((id)=>openNoteLexical(id));
// Keep the parent function under a distinct name; the extension's callback has its own scope.
const openNoteLexical=window.tramontoOpenPage;
$('previousPage').addEventListener('click',()=>navigatePage(-1).catch(e=>error(e.message)));
$('nextPage').addEventListener('click',()=>navigatePage(1).catch(e=>error(e.message)));
function fragmentAt(root,index){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let text;while((text=walker.nextNode())){if(index<=text.length)return [text,index];index-=text.length;}return [root,root.childNodes.length];}
function portions(root,index){const [end,offset]=fragmentAt(root,index),range=document.createRange();range.setStart(root,0);range.setEnd(end,offset);const head=node('div');head.appendChild(range.cloneContents());range.setStart(end,offset);range.setEnd(root,root.childNodes.length);const tail=node('div');tail.appendChild(range.cloneContents());return [head.innerHTML,tail.innerHTML];}
async function paginate(){if(!doc||paginating||activePane!=='text')return;const editor=$('richEditor');if(editor.scrollHeight<=editor.clientHeight+2)return;paginating=true;clearTimeout(saveTimer);$('noteEditor').inert=true;const original=editor.innerHTML,current=doc,style=getComputedStyle(editor),measure=editor.cloneNode(false);measure.removeAttribute('id');measure.removeAttribute('contenteditable');measure.style.cssText='position:absolute;left:-20000px;top:0;width:674px;height:960px;overflow:hidden;visibility:hidden;padding:0;border:0;box-sizing:border-box;min-height:0';measure.style.font=style.font;measure.style.lineHeight='28px';measure.className='rich-editor';$('a4Sheet').appendChild(measure);
 try{let rest=cleanHtml(original),pages=[];while(rest&&pages.length<60){measure.innerHTML=rest;if(measure.scrollHeight<=measure.clientHeight+2){pages.push(rest);rest='';break;}const source=node('div');source.innerHTML=rest;const total=source.textContent.length;if(!total)throw new Error('L’elemento è più alto di una pagina. Riduci la tabella o il blocco.');let low=0,high=total;while(low<high){const mid=Math.ceil((low+high)/2),[head]=portions(source,mid);measure.innerHTML=head;if(measure.scrollHeight<=measure.clientHeight+2)low=mid;else high=mid-1;}if(low<1)throw new Error('Un blocco non entra in A4: riduci il contenuto o la dimensione dei caratteri.');const text=source.textContent,space=text.lastIndexOf(' ',low);if(space>low-70&&space>0)low=space+1;const [head,tail]=portions(source,low);if(tail===rest)throw new Error('Impossibile suddividere questo blocco.');pages.push(head);rest=tail;}
 if(rest)throw new Error('Testo molto lungo: incolla al massimo 60 pagine per volta.');if(pages.length<2)return;
 // Create the continuation first, so a failed save cannot erase the original text.
 let lastId=null;for(let i=1;i<pages.length;i++){const content=clone(DEFAULT);content.font=current.content.font;content.paper=current.content.paper;content.html=pages[i];content.images=Array.from(new Set(Array.from(pages[i].matchAll(/\/api\/tramonto\/images\/(\d+)/g),m=>Number(m[1]))));const created=await api('/api/tramonto/notes','POST',{notebook_id:current.notebook_id,title:current.title+' · continua '+(i+1),subject:current.subject,content,copy_images_from:current.id});lastId=created.id;}
 editor.innerHTML=pages[0];changed();if(!await saveDoc())throw new Error('Le pagine successive sono salvate; verifica il salvataggio della prima pagina.');await loadBooks();await openNoteLexical(lastId,true);$('richEditor').focus();const range=document.createRange();range.selectNodeContents($('richEditor'));range.collapse(false);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('pageHint').textContent=pages.length+' pagine A4 salvate e numerate.';
 }catch(e){if(doc?.id===current.id){editor.innerHTML=original;changed();}error(e.message);}finally{measure.remove();paginating=false;$('noteEditor').inert=false;}}
$('splitPages').addEventListener('click',paginate);const schedulePages=()=>{clearTimeout(paginationTimer);paginationTimer=setTimeout(paginate,200);};$('richEditor').addEventListener('input',schedulePages);$('richEditor').addEventListener('paste',schedulePages);$('noteFont').addEventListener('change',schedulePages);
insert('pane-text','<div class="table-tools"><label>Righe <input id="tableRows" type="number" min="1" max="20" value="4"></label><label>Colonne <input id="tableCols" type="number" min="1" max="10" value="3"></label><button id="insertTable" class="secondary-button" type="button">+ Tabella</button><button id="addTableRow" class="secondary-button" type="button">+ Riga</button><button id="addTableCol" class="secondary-button" type="button">+ Colonna</button><label>Modello <select id="pageTemplate"><option value="">Scegli…</option><option value="lesson">Lezione</option><option value="cornell">Metodo Cornell</option><option value="lab">Relazione di laboratorio</option><option value="history">Analisi storica</option></select></label></div>');
let activeTable=null;$('richEditor').addEventListener('click',e=>{activeTable=e.target.closest('table');});
$('insertTable').addEventListener('click',()=>{const rows=Math.min(20,Math.max(1,Number($('tableRows').value)||4)),cols=Math.min(10,Math.max(1,Number($('tableCols').value)||3));let html='<table><tbody>';for(let r=0;r<rows;r++)html+='<tr>'+Array.from({length:cols},(_,c)=>r===0?'<th>Colonna '+(c+1)+'</th>':'<td>…</td>').join('')+'</tr>';html+='</tbody></table><p><br></p>';$('richEditor').focus();document.execCommand('insertHTML',false,html);changed();schedulePages();});
$('addTableRow').addEventListener('click',()=>{if(!activeTable||!activeTable.isConnected)return;const cols=activeTable.rows[0]?.cells.length||1;if(activeTable.rows.length>=20)return;const row=activeTable.insertRow();for(let c=0;c<cols;c++)row.insertCell().textContent='…';changed();schedulePages();});
$('addTableCol').addEventListener('click',()=>{if(!activeTable||!activeTable.isConnected||activeTable.rows[0].cells.length>=10)return;for(const row of activeTable.rows)row.insertCell().textContent='…';changed();schedulePages();});
$('pageTemplate').addEventListener('change',()=>{if(!doc)return;const templates={lesson:'<h2>Argomento della lezione</h2><p>Data · materia · fonti</p><h3>Idee principali</h3><p>…</p><h3>Da approfondire</h3><p>…</p>',cornell:'<h2>Domande e parole chiave</h2><p>…</p><h2>Appunti</h2><p>…</p><h3>Riassunto finale</h3><p>…</p>',lab:'<h2>Obiettivo</h2><p>…</p><h3>Materiali e procedimento</h3><p>…</p><h3>Misure e risultati</h3><p>…</p><h3>Conclusioni e limiti</h3><p>…</p>',history:'<h2>Evento e contesto</h2><p>…</p><h3>Cause · protagonisti · conseguenze</h3><p>…</p><h3>Fonti e interpretazioni</h3><p>…</p>'};const html=templates[$('pageTemplate').value];if(html){$('richEditor').focus();document.execCommand('insertHTML',false,html);changed();schedulePages();}$('pageTemplate').value='';});
async function collection(){if(!await saveDoc())return;await loadBooks();$('noteEditor').hidden=true;$('emptyNote').hidden=true;$('bookCollection').hidden=false;renderCollection();}
function renderCollection(){const grid=$('collectionGrid'),search=$('collectionSearch').value.toLocaleLowerCase();grid.replaceChildren();for(const book of books.filter(b=>b.title.toLocaleLowerCase().includes(search))){const card=button('',async()=>{bookId=book.id;$('bookCollection').hidden=true;doc=null;await loadBooks();await loadNotes();if(notes.length)await openNoteLexical(notes[0].id,true);else{$('emptyNote').hidden=false;}});card.className='notebook-cover cover-'+(book.id%5);const cover=node('span','◒');cover.className='cover-symbol';card.append(cover,node('strong',book.title),node('small',book.note_count+' pagine · Apri quaderno →'));grid.appendChild(card);}if(!grid.children.length)grid.appendChild(node('p','Nessun quaderno con questo nome.'));}
$('showCollection').addEventListener('click',()=>collection().catch(e=>error(e.message)));$('collectionSearch').addEventListener('input',renderCollection);
insert('pane-math','<div class="math-section"><h3>Dal calcolo all’idea.</h3><p class="tool-note">Radianti · seno, coseno, tangente, inverse e iperboliche, radici, logaritmi, esponenziali, min e max.</p><div class="calculus-tools"><label>f(x)<input id="calcExpression" value="x^2" maxlength="250"></label><label>x / estremo a<input id="calcA" type="number" value="0" step="any"></label><label>Estremo b<input id="calcB" type="number" value="1" step="any"></label></div><div class="tool-actions"><button id="calculateValue" class="secondary-button">Valore f(a)</button><button id="calculateDerivative" class="secondary-button">Derivata simbolica</button><button id="calculateIntegral" class="secondary-button">Integrale numerico</button><button id="calculateRoot" class="secondary-button">Zero nell’intervallo</button></div><p id="calculusResult" role="status" class="tool-message"></p></div>');
const calculus=action=>{try{const expression=$('calcExpression').value,fn=expressionFunction(expression),a=Number($('calcA').value),b=Number($('calcB').value);if(!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a)>10000||Math.abs(b)>10000)throw Error('Estremi finiti tra −10000 e 10000.');let result;
 if(action==='value')result='f('+a+') = '+fn(a);
 if(action==='derivative')result="f′(x) = "+math.derivative(expression,'x').toString();
 if(action==='integral'){if(a>=b)throw Error('Scegli a < b.');const n=1000,h=(b-a)/n;let sum=fn(a)+fn(b);for(let i=1;i<n;i++)sum+=(i%2?4:2)*fn(a+i*h);if(!Number.isFinite(sum))throw Error('Campioni non finiti: controlla dominio e discontinuità.');result='∫ da '+a+' a '+b+' ≈ '+(sum*h/3).toPrecision(10)+' · Simpson, 1000 intervalli; stima numerica.';}
 if(action==='root'){let lo=a,hi=b,flo=fn(lo),fhi=fn(hi);if(lo>=hi||!Number.isFinite(flo)||!Number.isFinite(fhi)||flo*fhi>0)throw Error('Serve un intervallo crescente con valori finiti e segno diverso.');for(let i=0;i<50;i++){const mid=(lo+hi)/2,fm=fn(mid);if(!Number.isFinite(fm))throw Error('Discontinuità rilevata nell’intervallo.');if(flo*fm<=0){hi=mid;fhi=fm;}else{lo=mid;flo=fm;}}const value=(lo+hi)/2;if(Math.abs(fn(value))>1e-5)throw Error('Possibile discontinuità: non confermo uno zero.');result='x ≈ '+value.toPrecision(10)+' · bisezione numerica.';}
 $('calculusResult').textContent=result;
 }catch(e){$('calculusResult').textContent=e.message;}};
for(const [id,action]of [['calculateValue','value'],['calculateDerivative','derivative'],['calculateIntegral','integral'],['calculateRoot','root']])$(id).addEventListener('click',()=>calculus(action));
const formulas=[['Derivata','\\frac{d}{dx}f(x)'],['Matrice','\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}'],['Sistema','\\begin{cases}x+y=1\\\\x-y=0\\end{cases}'],['Fourier','X(f)=\\int_{-\\infty}^{+\\infty}x(t)e^{-j2\\pi ft}dt'],['Logaritmo','\\log_a x=\\frac{\\ln x}{\\ln a}'],['Binomio','\\binom{n}{k}=\\frac{n!}{k!(n-k)!}']];for(const [title,value]of formulas)document.querySelector('.formula-snippets').appendChild(button(title,()=>{$('formulaInput').value=value;latex($('formulaPreview'),value);}));
// Additional electronic devices, with an explicit terminal layout shared with the server.
const two=[[-28,0],[28,0]],three=[[-28,0],[20,-25],[20,25]],box='M-28 0h8M20 0h8M-20-18h40v36h-40z';
const extra={battery:['Batteria','V','9V',two,'M-28 0h20M-8-18v36M3-10v20M3 0h25'],current:['Sorgente di corrente','I','1mA',two,'M-28 0h10M18 0h10M-10 0h20l-7-5m7 5-7 5'],function:['Generatore di funzioni','V','1kHz',two,'M-28 0h10M18 0h10M-10 7v-14H0V7H10V-7'],pot:['Potenziometro','R','10k',[[ -28,0],[28,0],[0,28]],box+'M0 28V8l-5 6m5-6 5 6'],led:['LED','D','',two,PARTS.diode.path+'M3-22l10-10m-10 2 10-2-2 10'],zener:['Zener','D','',two,PARTS.diode.path+'M9-14h6M9 14H3'],pnp:['Transistor PNP','Q','PNP',three,PARTS.npn.path],nmos:['MOSFET N','M','NMOS',three,'M-28 0h12M-16-17v34M-10-17v34M-10-7 20-25M-10 7 20 25'],pmos:['MOSFET P','M','PMOS',three,'M-28 0h12M-16-17v34M-10-17v34M-10-7 20-25M-10 7 20 25'],transformer:['Trasformatore','T','1mH',[[-28,-18],[-28,18],[28,-18],[28,18]],'M-28-18h15v36h-15M28-18H13v36h15M-4-23v46M4-23v46'],ammeter:['Amperometro','A','',two,box],voltmeter:['Voltmetro','VM','',two,box],scope:['Oscilloscopio','OSC','',two,box+'M-13 3l6-10 8 17 7-11'],probe:['Sonda','P','',[[0,0]],'M0 0v-18l12-12M0-18l-12-12M-12-30h24'],fuse:['Fusibile','F','0.01',two,box+'M-20 0h40'],and:['Porta AND','U','',[[ -28,-12],[-28,12],[28,0],[0,-32],[0,32]],box],or:['Porta OR','U','',[[ -28,-12],[-28,12],[28,0],[0,-32],[0,32]],box],not:['Porta NOT','U','',[[-28,0],[28,0],[0,-32],[0,32]],'M-28 0h10M-18-17v34L12 0-18-17M12 0h16']};
for(const [type,[name,prefix,value,ports,path]]of Object.entries(extra)){PARTS[type]={name,prefix,value,ports,path,circle:['current','function'].includes(type)};const b=button(name,()=>{});b.dataset.component=type;document.querySelector('.component-palette').appendChild(b);}
insert('componentForm','<div id="sourceParams" hidden><label>Forma<select id="sourceWave"><option value="sine">Sinusoide</option><option value="square">Quadra</option><option value="triangle">Triangolare</option></select></label><label>Frequenza Hz<input id="sourceFrequency" type="number" min="0.001" max="1000000000" value="1000" step="any"></label><label>Ampiezza V<input id="sourceAmplitude" type="number" min="0" max="1000000" value="1" step="any"></label><label>Offset V<input id="sourceOffset" type="number" value="0" step="any"></label><label>Duty %<input id="sourceDuty" type="number" min="1" max="99" value="50" step="any"></label></div><label id="switchParams" hidden><input id="switchClosed" type="checkbox"> Interruttore chiuso</label>');
function component(part){$('sourceParams').hidden=!part||!['function','ac'].includes(part.type);$('switchParams').hidden=!part||part.type!=='switch';if(!part)return;const p=part.params||{};for(const [id,key,def]of [['sourceFrequency','frequency',1000],['sourceAmplitude','amplitude',1],['sourceOffset','offset',0],['sourceDuty','duty',50]])$(id).value=key==='duty'?(p[key]||.5)*100:(p[key]??def);$('sourceWave').value=p.wave||'sine';$('switchClosed').checked=p.closed===true;}
function updateComponent(part){if(['function','ac'].includes(part.type))part.params={frequency:Number($('sourceFrequency').value),amplitude:Number($('sourceAmplitude').value),offset:Number($('sourceOffset').value),duty:Number($('sourceDuty').value)/100,wave:$('sourceWave').value};if(part.type==='switch')part.params={closed:$('switchClosed').checked};}
insert('pane-circuit','<section class="simulation-panel"><div class="panel-heading"><div><span class="eyebrow">LABORATORIO LOCALE</span><h3>Misura quello che hai disegnato.</h3></div><span id="spiceEngine" class="private-badge">ngspice</span></div><div class="simulation-settings"><label>Analisi<select id="spiceAnalysis"><option value="op">Punto di lavoro DC</option><option value="tran">Transitorio</option><option value="ac">Sweep AC</option><option value="dc">Sweep DC</option></select></label><label>Durata s<input id="spiceStop" type="number" value="0.01" min="0.000000001" max="100" step="any"></label><label>Campioni<input id="spiceSamples" type="number" value="500" min="20" max="2000"></label><label>Frequenza da Hz<input id="spiceStart" type="number" value="1" step="any"></label><label>Frequenza a Hz<input id="spiceEnd" type="number" value="100000" step="any"></label><label>Sweep DC da V<input id="spiceFrom" type="number" value="0" step="any"></label><label>Sweep DC a V<input id="spiceTo" type="number" value="5" step="any"></label></div><div class="tool-actions"><button id="simulateCircuit" class="primary-button">▶ Simula</button><button id="stopSimulation" class="secondary-button" disabled>■ Interrompi</button><button id="downloadNetlist" class="secondary-button">Netlist .cir</button><button id="downloadSpiceCsv" class="secondary-button" disabled>Risultati CSV</button><select id="circuitExample" aria-label="Esempio elettronico"><option value="">Carica esempio…</option><option value="divider">Divisore 5 V → 2,5 V</option><option value="rc">Filtro RC · sinusoide</option></select></div><p id="simulationStatus" role="status" class="tool-message"></p><div id="simulationResult"></div><p class="tool-note">Serve almeno una sorgente e una massa. Per misurare un nodo aggiungi una sonda. Amperometri in serie, voltmetri e oscilloscopi in parallelo. I modelli di transistor, opamp e porte sono semplificati; non rappresentano un componente commerciale.</p></section>');
function spiceOptions(){return{analysis:$('spiceAnalysis').value,stop:Number($('spiceStop').value),samples:Number($('spiceSamples').value),start:Number($('spiceStart').value),end:Number($('spiceEnd').value),dc_start:Number($('spiceFrom').value),dc_end:Number($('spiceTo').value),points:30};}
let lastSimulation=null;
async function poll(){if(!job)return;try{const result=await api('/api/tramonto/simulations/'+job);if(!result.done){pollTimer=setTimeout(poll,650);return;}job=null;$('simulateCircuit').disabled=false;$('stopSimulation').disabled=true;if(result.result&&!result.result.error){lastSimulation=result.result;renderSimulation(result.result);$('simulationStatus').textContent='Simulazione completata · '+result.result.engine;$('downloadSpiceCsv').disabled=false;}else $('simulationStatus').textContent=result.result?.error||'Simulazione interrotta.';}catch(e){job=null;$('simulateCircuit').disabled=false;$('stopSimulation').disabled=true;$('simulationStatus').textContent=e.message;}}
$('simulateCircuit').addEventListener('click',async()=>{try{if(!doc||!await saveDoc())return;$('simulateCircuit').disabled=true;const result=await api('/api/tramonto/simulations','POST',{note_id:doc.id,options:spiceOptions()});job=result.job_id;$('stopSimulation').disabled=false;$('simulationStatus').textContent='Simulazione in corso…';poll();}catch(e){$('simulateCircuit').disabled=false;$('simulationStatus').textContent=e.message;}});
$('stopSimulation').addEventListener('click',async()=>{if(job)await api('/api/tramonto/simulations/'+job+'/cancel','POST',{});clearTimeout(pollTimer);job=null;$('stopSimulation').disabled=true;$('simulateCircuit').disabled=false;$('simulationStatus').textContent='Simulazione interrotta.';});
function download(value,type,name){const url=URL.createObjectURL(new Blob([value],{type})),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('downloadNetlist').addEventListener('click',async()=>{try{if(!doc||!await saveDoc())return;const result=await api('/api/tramonto/netlist','POST',{note_id:doc.id,options:spiceOptions()});download(result.netlist,'text/plain','tramonto.cir');}catch(e){$('simulationStatus').textContent=e.message;}});
$('downloadSpiceCsv').addEventListener('click',()=>{if(!lastSimulation)return;const r=lastSimulation,lines=[['x',...r.series.map(s=>s.name+' ('+s.unit+')')].join(',')];r.x.forEach((x,i)=>lines.push([x,...r.series.map(s=>s.values[i])].join(',')));download(lines.join('\n'),'text/csv','simulazione.csv');});
function renderSimulation(r){const target=$('simulationResult');target.replaceChildren();const table=node('table');table.className='lab-table';const header=node('tr');header.append(node('th','Traccia'),node('th','Primo valore'),node('th','Ultimo valore'));table.appendChild(header);for(const s of r.series){const row=node('tr');row.append(node('td',s.name+' · '+s.unit),node('td',Number(s.values[0]).toPrecision(6)),node('td',Number(s.values.at(-1)).toPrecision(6)));table.appendChild(row);}target.appendChild(table);if(r.x.length<2)return;const svg=svgNode('svg',{viewBox:'0 0 800 360',class:'simulation-plot','aria-label':'Risultati della simulazione'}),lo=Math.min(...r.series.flatMap(s=>s.values)),hi=Math.max(...r.series.flatMap(s=>s.values)),xmin=r.x[0],xmax=r.x.at(-1),colors=['#347c9d','#dc8a50','#8772ad','#5a9672','#d36776','#8f753c'];const span=hi-lo||1;svg.appendChild(svgNode('rect',{width:800,height:360,fill:'#fffdf7',rx:12}));svg.appendChild(svgNode('path',{d:'M55 20V320H780',stroke:'#8b9797',fill:'none'}));r.series.forEach((s,j)=>{const path=s.values.map((v,i)=>(i?'L':'M')+(55+(r.x[i]-xmin)/(xmax-xmin)*725).toFixed(2)+' '+(320-(v-lo)/span*270).toFixed(2)).join(' ');svg.appendChild(svgNode('path',{d:path,stroke:colors[j%6],fill:'none','stroke-width':2}));svg.appendChild(svgNode('text',{x:60+(j%3)*240,y:14+Math.floor(j/3)*14,fill:colors[j%6],'font-size':11},s.name+' ('+s.unit+')'));});svg.appendChild(svgNode('text',{x:58,y:345,fill:'#667','font-size':10},'x '+xmin.toPrecision(3)+' → '+xmax.toPrecision(3)+' · y '+lo.toPrecision(3)+' → '+hi.toPrecision(3)));target.appendChild(svg);target.appendChild(node('small',r.total_samples+' campioni · visualizzati '+r.x.length+' · '+(r.analysis==='ac'?'modulo delle tensioni, frequenza in Hz':r.analysis==='tran'?'tempo in secondi':r.analysis==='dc'?'tensione di sweep in V':'punto di lavoro')));}
function circuitExample(kind){if(!doc)return;if(doc.content.circuit.components.length&&!confirm('Sostituire lo schema con l’esempio? Puoi annullare con «Annulla».'))return;historyCircuit();const part=(id,type,x,y,value,params)=>({id,type,x,y,rotation:0,label:id,value,params:params||{}}),wire=(a,ap,b,bp)=>({id:crypto.randomUUID(),from:{component:a,port:ap},to:{component:b,port:bp}});doc.content.circuit={components:[part('V1',kind==='rc'?'function':'voltage',150,160,kind==='rc'?'1kHz':'5V'),part('R1','resistor',400,160,'1k'),part(kind==='rc'?'C1':'R2',kind==='rc'?'capacitor':'resistor',650,160,kind==='rc'?'1uF':'1k'),part('GND','ground',150,350,''),part('P1','probe',530,160,'')],wires:[wire('V1',0,'R1',0),wire('R1',1,kind==='rc'?'C1':'R2',0),wire(kind==='rc'?'C1':'R2',1,'GND',0),wire('V1',1,'GND',0),wire('P1',0,'R1',1)]};renderCircuit();changed();$('spiceAnalysis').value=kind==='rc'?'tran':'op';}
$('circuitExample').addEventListener('change',()=>{if($('circuitExample').value)circuitExample($('circuitExample').value);$('circuitExample').value='';});
api('/api/tramonto/labs').then(r=>{const available=r.spice_available;$('spiceEngine').textContent=available?'ngspice · pronto':'ngspice da installare';$('simulateCircuit').disabled=!available;}).catch(()=>{});
insert('pane-network','<div class="network-heading"><span class="eyebrow">SISTEMI E RETI</span><h3>Un pacchetto, un percorso.</h3><p class="tool-note">Topologie e simboli di rete ispirati ai laboratori Cisco. Simulatore didattico IPv4 locale: non esegue IOS e non invia pacchetti sulla rete reale.</p></div><div id="networkPalette" class="component-palette"></div><div class="tool-actions"><button id="networkSelect" class="secondary-button">Sposta</button><button id="networkWire" class="secondary-button">Collega</button><select id="networkCable" aria-label="Tipo di collegamento"><option value="ethernet">Ethernet</option><option value="fiber">Fibra</option><option value="serial">Seriale</option><option value="wifi">Wi-Fi</option></select><button id="networkDelete" class="secondary-button">Elimina selezione</button><button id="networkUndo" class="secondary-button">Annulla</button><button id="networkExample" class="secondary-button">Esempio LAN</button><button id="exportNetwork" class="secondary-button">SVG</button></div><svg id="networkSvg" viewBox="0 0 1000 640" role="application" aria-label="Editor di topologie di rete" tabindex="0"></svg><form id="networkForm" class="component-properties" hidden><label>Nome<input id="networkName" maxlength="60"></label><label>IPv4 / prefisso<input id="networkIp" placeholder="192.168.1.2/24" maxlength="50"></label><label>Gateway<input id="networkGateway" placeholder="192.168.1.1" maxlength="50"></label><label>VLAN<input id="networkVlan" type="number" min="1" max="4094" value="1"></label><label>Interfacce router (CIDR, una per riga)<textarea id="networkInterfaces" maxlength="500" placeholder="192.168.1.1/24"></textarea></label><label><input id="networkEnabled" type="checkbox" checked> Dispositivo / collegamento attivo</label><button class="secondary-button">Salva dispositivo</button></form><div class="simulation-panel"><h3>Verifica la comunicazione.</h3><div class="tool-actions"><label>Da<select id="pingSource"></select></label><label>A<select id="pingTarget"></select></label><button id="networkPing" class="primary-button">▶ Ping simulato</button></div><p id="networkResult" role="status" class="tool-message"></p><form id="networkCli"><label>Console didattica<input id="networkCommand" maxlength="150" placeholder="show ip interface brief / show vlan brief / ping 192.168.1.2"></label><button class="secondary-button">Esegui</button></form><pre id="networkConsole" class="network-console"></pre></div><div class="math-section"><h3>Indirizzi, senza confondersi.</h3><div class="tool-actions"><label>IPv4 / CIDR<input id="subnetInput" value="192.168.1.20/24"></label><button id="subnetCalculate" class="secondary-button">Calcola sottorete</button></div><p id="subnetResult" class="tool-message" role="status"></p></div>');
const netKinds={router:'Router',switch:'Switch',pc:'PC',server:'Server',laptop:'Laptop',accesspoint:'Access point',firewall:'Firewall',cloud:'Cloud',printer:'Stampante'};
const netIcons={router:'M-20 0h40m-8-7 8 7-8 7M0-20v40m-7-8 7 8 7-8',switch:'M-20-8h40m-40 16h40M-12-18v36M0-18v36M12-18v36',pc:'M-24-18h48v32h-48zM0 14v12m-15 0h30',server:'M-19-25h38v50h-38zM-19-8h38M-19 8h38M-12-17h5M-12 0h5M-12 17h5',laptop:'M-21-20h42v32h-42zM-21 12l-10 10h62l-10-10',accesspoint:'M0 20V0M-20-4q20-28 40 0M-13 2q13-20 26 0M-5 7q5-9 10 0',firewall:'M-23-22h46v44h-46zM-23-8h46M-23 7h46M0-22v14M-12-8V7M12-8V7M0 7v15',cloud:'M-23 13q-20-18 0-25q10-25 26-8q23-7 23 11q20 19-3 22z',printer:'M-17-22h34v20h-34zM-25-4h50v25h-50zM-17 12h34v15h-34'};
function network(){if(!doc)return{nodes:[],links:[]};return doc.content.network||(doc.content.network={nodes:[],links:[]});}
function netSnapshot(){netHistory.push(clone(network()));netHistory=netHistory.slice(-20);}
for(const [kind,title]of Object.entries(netKinds))$('networkPalette').appendChild(button(title,()=>{netMode='place';netType=kind;$('networkResult').textContent='Tocca il foglio per aggiungere '+title+'.';}));
function renderNetwork(){const svg=$('networkSvg'),net=network();svg.replaceChildren();svg.appendChild(svgNode('rect',{width:1000,height:640,rx:12,fill:'#f1f7fc'}));
for(const link of net.links){const a=net.nodes.find(n=>n.id===link.from),b=net.nodes.find(n=>n.id===link.to);if(!a||!b)continue;svg.appendChild(svgNode('path',{d:'M'+a.x+' '+a.y+'L'+b.x+' '+b.y,stroke:link.id===netSelected?'#dd8b50':!link.enabled?'#b4bdc5':link.kind==='fiber'?'#aa79c4':'#5482a0','stroke-width':link.id===netSelected?6:4,'stroke-dasharray':['wifi','serial'].includes(link.kind)?'8 6':'none','data-link-id':link.id,fill:'none'}));}
for(const n of net.nodes){const g=svgNode('g',{'data-net-id':n.id,transform:'translate('+n.x+' '+n.y+')',class:'network-node'});g.appendChild(svgNode(n.type==='router'?'circle':'rect',n.type==='router'?{r:35,fill:n.enabled?'#2776a2':'#8a99a4',stroke:netSelected===n.id?'#e19756':'#195875','stroke-width':3}:{x:-38,y:-35,width:76,height:70,rx:n.type==='cloud'?30:10,fill:n.enabled?'#2776a2':'#8a99a4',stroke:netSelected===n.id?'#e19756':'#195875','stroke-width':3}));g.appendChild(svgNode('path',{d:netIcons[n.type],fill:'none',stroke:'#fff','stroke-width':2.4,'stroke-linecap':'round','stroke-linejoin':'round'}));svg.appendChild(g);svg.appendChild(svgNode('text',{x:n.x,y:n.y+51,'text-anchor':'middle',fill:'#34546c','font-size':13},n.name));if(n.ip)svg.appendChild(svgNode('text',{x:n.x,y:n.y+66,'text-anchor':'middle',fill:'#6f8999','font-size':10},n.ip));}
const selected=net.nodes.find(n=>n.id===netSelected),link=net.links.find(l=>l.id===netSelected);$('networkForm').hidden=!selected&&!link;if(selected){$('networkName').value=selected.name;$('networkIp').value=selected.ip;$('networkGateway').value=selected.gateway;$('networkVlan').value=selected.vlan;$('networkInterfaces').value=selected.interfaces.join('\n');$('networkEnabled').checked=selected.enabled;}else if(link){$('networkName').value=link.kind;$('networkIp').value='';$('networkGateway').value='';$('networkInterfaces').value='';$('networkEnabled').checked=link.enabled;}
for(const id of ['pingSource','pingTarget']){const old=$(id).value;$(id).replaceChildren();for(const n of net.nodes){const option=node('option',n.name);option.value=n.id;$(id).appendChild(option);}if(net.nodes.some(n=>n.id===old))$(id).value=old;}
}
function netPoint(event){const svg=$('networkSvg'),point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const p=point.matrixTransform(svg.getScreenCTM().inverse());return{x:Math.max(40,Math.min(960,Math.round(p.x/10)*10)),y:Math.max(40,Math.min(600,Math.round(p.y/10)*10))};}
$('networkSelect').addEventListener('click',()=>{netMode='select';netStart=null;});$('networkWire').addEventListener('click',()=>{netMode='wire';netStart=null;$('networkResult').textContent='Tocca due dispositivi per collegarli.';});
$('networkSvg').addEventListener('pointerdown',event=>{if(!doc)return;event.preventDefault();const net=network(),hit=event.target.closest('[data-net-id]'),link=event.target.closest('[data-link-id]');if(netMode==='wire'&&hit){const id=hit.dataset.netId;if(!netStart){netStart=id;$('networkResult').textContent='Scegli il secondo dispositivo.';}else if(netStart!==id){if(net.links.length>=160)return;netSnapshot();net.links.push({id:crypto.randomUUID(),from:netStart,to:id,kind:$('networkCable').value,enabled:true});netStart=null;changed();renderNetwork();}return;}if(netMode==='place'&&!hit&&!link){if(net.nodes.length>=80)return;netSnapshot();const point=netPoint(event),id=crypto.randomUUID();net.nodes.push({id,type:netType,...point,name:netKinds[netType]+' '+(net.nodes.filter(n=>n.type===netType).length+1),ip:'',gateway:'',vlan:1,enabled:true,interfaces:[]});netSelected=id;changed();renderNetwork();return;}if(hit){netSelected=hit.dataset.netId;const n=net.nodes.find(n=>n.id===netSelected),p=netPoint(event);netSnapshot();netDrag={id:n.id,dx:n.x-p.x,dy:n.y-p.y};$('networkSvg').setPointerCapture(event.pointerId);}else netSelected=link?.dataset.linkId||null;renderNetwork();});
$('networkSvg').addEventListener('pointermove',event=>{if(!netDrag)return;const n=network().nodes.find(n=>n.id===netDrag.id),p=netPoint(event);n.x=Math.max(40,Math.min(960,p.x+netDrag.dx));n.y=Math.max(40,Math.min(600,p.y+netDrag.dy));renderNetwork();});for(const e of ['pointerup','pointercancel'])$('networkSvg').addEventListener(e,()=>{if(netDrag)changed();netDrag=null;});
$('networkDelete').addEventListener('click',()=>{if(!netSelected)return;netSnapshot();const net=network();net.nodes=net.nodes.filter(n=>n.id!==netSelected);net.links=net.links.filter(l=>l.id!==netSelected&&l.from!==netSelected&&l.to!==netSelected);netSelected=null;renderNetwork();changed();});$('networkUndo').addEventListener('click',()=>{if(doc&&netHistory.length){doc.content.network=netHistory.pop();netSelected=null;renderNetwork();changed();}});
$('networkForm').addEventListener('submit',event=>{event.preventDefault();try{const n=network().nodes.find(n=>n.id===netSelected),link=network().links.find(l=>l.id===netSelected);if(n){if($('networkIp').value)cidr($('networkIp').value);if($('networkGateway').value)ipNumber($('networkGateway').value);const interfaces=$('networkInterfaces').value.split(/[,\n]/).map(s=>s.trim()).filter(Boolean);if(interfaces.length>8)throw Error('Massimo otto interfacce.');interfaces.forEach(cidr);netSnapshot();Object.assign(n,{name:$('networkName').value,ip:$('networkIp').value.trim(),gateway:$('networkGateway').value.trim(),vlan:Number($('networkVlan').value),interfaces,enabled:$('networkEnabled').checked});}else if(link){netSnapshot();link.enabled=$('networkEnabled').checked;}changed();renderNetwork();}catch(e){$('networkResult').textContent=e.message;}});
function ipNumber(s){if(typeof s!=='string'||!/^\d{1,3}(\.\d{1,3}){3}$/.test(s)||s.split('.').some(n=>Number(n)>255))throw Error('IPv4 non valido.');return s.split('.').reduce((v,n)=>v*256+Number(n),0)>>>0;}
const ipText=n=>[24,16,8,0].map(bits=>(n>>>bits)&255).join('.');
function cidr(s){const [ip,prefix]=s.split('/');if(prefix===undefined||!/^\d{1,2}$/.test(prefix)||Number(prefix)>32)throw Error('Usa IPv4/prefisso, ad esempio 192.168.1.2/24.');const n=ipNumber(ip),p=Number(prefix),mask=p===0?0:(0xffffffff<<(32-p))>>>0,start=(n&mask)>>>0,size=2**(32-p);return{ip:n,prefix:p,mask,start,end:start+size-1,size};}
function trace(sourceId,targetId){const net=network(),source=net.nodes.find(n=>n.id===sourceId),target=net.nodes.find(n=>n.id===targetId);if(!source||!target||source.id===target.id)throw Error('Scegli due dispositivi diversi.');if(!source.enabled||!target.enabled)throw Error('Un dispositivo è disattivato.');const a=cidr(source.ip),b=cidr(target.ip),same=(a.ip&b.mask)===(b.ip&b.mask)&&(a.ip&a.mask)===(b.ip&a.mask),routes=[];
const queue=[[source.id]],seen=new Set();while(queue.length){const path=queue.shift(),id=path.at(-1);if(seen.has(id))continue;seen.add(id);if(id===target.id){routes.push(path);break;}const current=net.nodes.find(n=>n.id===id);if(id!==source.id&&!['switch','router','accesspoint','firewall','cloud'].includes(current.type))continue;for(const link of net.links.filter(l=>l.enabled&&(l.from===id||l.to===id))){const other=link.from===id?link.to:link.from,n=net.nodes.find(v=>v.id===other);if(n?.enabled&&!path.includes(other)&&(current.type==='router'||n.type==='router'||current.vlan===n.vlan))queue.push([...path,other]);}}
if(!routes.length)throw Error('Nessun percorso attivo: verifica cavi, VLAN e dispositivi.');const path=routes[0],routers=path.map(id=>net.nodes.find(n=>n.id===id)).filter(n=>n.type==='router');if(!same){if(routers.length!==1)throw Error('Tra sottoreti diverse serve un solo router con due interfacce. Il routing tra più router richiede configurazione non supportata.');const router=routers[0],interfaces=[router.ip,...router.interfaces].filter(Boolean).map(cidr),ga=ipNumber(source.gateway),gb=ipNumber(target.gateway);if(!interfaces.some(i=>i.ip===ga&&(a.ip&i.mask)===i.start)||!interfaces.some(i=>i.ip===gb&&(b.ip&i.mask)===i.start))throw Error('Gateway o interfacce router non corrispondono alle due sottoreti.');}else if(source.vlan!==target.vlan)throw Error('VLAN diverse: usa sottoreti e router distinti.');return path;}
function ping(){try{const path=trace($('pingSource').value,$('pingTarget').value),net=network();$('networkResult').textContent='ICMP simulato: risposta ricevuta · '+path.map(id=>net.nodes.find(n=>n.id===id).name).join(' → ')+' · '+(path.length-1)+' collegamenti. Nessun tempo di rete reale misurato.';const svg=$('networkSvg'),packet=svgNode('circle',{r:8,fill:'#edab58',stroke:'#fff','stroke-width':2});svg.appendChild(packet);const coords=path.map(id=>net.nodes.find(n=>n.id===id)),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:1200,start=performance.now();function tick(now){if(!packet.isConnected)return;const fraction=duration?Math.min(1,(now-start)/duration):1,position=fraction*(coords.length-1),i=Math.min(coords.length-2,Math.floor(position)),local=position-i;packet.setAttribute('cx',coords[i].x+(coords[i+1].x-coords[i].x)*local);packet.setAttribute('cy',coords[i].y+(coords[i+1].y-coords[i].y)*local);if(fraction<1)requestAnimationFrame(tick);else setTimeout(()=>packet.remove(),400);}requestAnimationFrame(tick);}catch(e){$('networkResult').textContent=e.message;}}
$('networkPing').addEventListener('click',ping);$('subnetCalculate').addEventListener('click',()=>{try{const n=cidr($('subnetInput').value),hosts=n.prefix>=31?n.size:n.size-2;$('subnetResult').textContent='Rete '+ipText(n.start)+'/'+n.prefix+' · maschera '+ipText(n.mask)+' · broadcast '+ipText(n.end)+' · '+hosts+' indirizzi utilizzabili'+(n.prefix===31?' (collegamento punto-punto)':n.prefix===32?' (singolo host)':'');}catch(e){$('subnetResult').textContent=e.message;}});
$('networkCli').addEventListener('submit',event=>{event.preventDefault();const command=$('networkCommand').value.trim().toLowerCase(),net=network();if(command==='show ip interface brief')$('networkConsole').textContent=net.nodes.map(n=>n.name.padEnd(20)+' '+(n.ip||'unassigned')+' '+(n.enabled?'up':'down')+' '+n.interfaces.join(', ')).join('\n');else if(command==='show vlan brief')$('networkConsole').textContent=net.nodes.map(n=>'VLAN '+n.vlan+' · '+n.name).join('\n');else if(command==='show running-config')$('networkConsole').textContent=net.nodes.map(n=>'hostname '+n.name+'\ninterface ethernet0\n ip address '+(n.ip||'unassigned')+'\n vlan '+n.vlan+'\n '+(n.enabled?'no shutdown':'shutdown')).join('\n\n');else if(command.startsWith('ping ')){const target=net.nodes.find(n=>n.ip.split('/')[0]===command.slice(5));if(target){$('pingTarget').value=target.id;ping();$('networkConsole').textContent=$('networkResult').textContent;}else $('networkConsole').textContent='Destinazione assente nella topologia.';}else $('networkConsole').textContent='Comandi disponibili: show ip interface brief, show vlan brief, show running-config, ping IPv4. Console simulata.';});
$('networkExample').addEventListener('click',()=>{if(!doc)return;if(network().nodes.length&&!confirm('Sostituire la topologia? Puoi annullare.'))return;netSnapshot();const make=(id,type,x,y,ip)=>({id,type,x,y,ip,name:id,gateway:'192.168.1.1',vlan:1,enabled:true,interfaces:[]});doc.content.network={nodes:[make('PC1','pc',220,300,'192.168.1.2/24'),make('SW1','switch',500,300,''),make('PC2','pc',780,300,'192.168.1.3/24'),make('R1','router',500,140,'192.168.1.1/24')],links:[{id:'L1',from:'PC1',to:'SW1',kind:'ethernet',enabled:true},{id:'L2',from:'SW1',to:'PC2',kind:'ethernet',enabled:true},{id:'L3',from:'SW1',to:'R1',kind:'ethernet',enabled:true}]};renderNetwork();$('pingSource').value='PC1';$('pingTarget').value='PC2';changed();});$('exportNetwork').addEventListener('click',()=>exportSvg('networkSvg','topologia.svg'));
window.TramontoLab={openNote,fitPage,restorePosition,component,updateComponent,trace,cidr,paginate};
// Insert uploaded assets and laboratory snapshots into the main document at the caret.
let savedRange=null,selectedImage=null,draggedImage=null;
document.addEventListener('selectionchange',()=>{const s=getSelection();if(s.rangeCount&&$('richEditor').contains(s.anchorNode))savedRange=s.getRangeAt(0).cloneRange();});
function restoreCaret(){const editor=$('richEditor');editor.focus();const selection=getSelection(),range=savedRange&&editor.contains(savedRange.startContainer)?savedRange.cloneRange():document.createRange();if(!savedRange||!editor.contains(range.startContainer)){range.selectNodeContents(editor);range.collapse(false);}selection.removeAllRanges();selection.addRange(range);return range;}
function showText(){const b=document.querySelector('[data-pane=text]');b.click();fitPage();}
function insertExisting(id){if(!doc||!doc.content.images.includes(id))return;showText();const range=restoreCaret(),image=node('img');image.src='/api/tramonto/images/'+id;image.width=450;image.alt='Immagine del quaderno';image.dataset.layout='inline';image.draggable=true;range.deleteContents();range.insertNode(image);range.setStartAfter(image);range.collapse(true);savedRange=range;changed();schedulePages();image.addEventListener('load',schedulePages,{once:true});}
async function insertFile(file){if(!doc||uploading)return;const current=doc;if(file.size>8*1024*1024){error('Massimo 8 MB per immagine.');return;}if(current.content.images.length>=30){error('Massimo trenta immagini per pagina.');return;}if(!await saveDoc())return;uploading=true;$('saveStatus').textContent='Importazione immagine…';try{const response=await fetch('/api/tramonto/notes/'+current.id+'/images',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type||'image/png','X-CSRF-Token':csrf,'X-Image-Name':encodeURIComponent((file.name||'Laboratorio.png').slice(0,180))},body:file}),data=await response.json();if(!response.ok)throw Error(data.error||'Immagine non valida.');current.content.images.push(data.id);if(current===doc){insertExisting(data.id);renderImages();}}catch(e){error(e.message);}finally{uploading=false;if(current===doc)await saveDoc();}}
insert('pane-text','<div class="word-insert"><label class="secondary-button image-import">▧ Immagine nel testo<input id="inlineImageInput" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label><span class="tool-note">Incolla anche immagini dagli appunti, oppure trascinale sul foglio.</span><div id="imageInspector" hidden><label>Larghezza px<input id="inlineImageWidth" type="number" min="40" max="674" value="450"></label><label>Disposizione<select id="inlineImageLayout"><option value="inline">Nel testo</option><option value="left">A sinistra · testo a fianco</option><option value="right">A destra · testo a fianco</option><option value="center">Centrata</option></select></label><button id="removeInlineImage" class="secondary-button" type="button">Rimuovi dal testo</button></div></div>');
$('inlineImageInput').addEventListener('change',async e=>{if(e.target.files[0])await insertFile(e.target.files[0]);e.target.value='';});
$('richEditor').addEventListener('paste',e=>{const file=Array.from(e.clipboardData.files).find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();insertFile(file);}});
$('richEditor').addEventListener('click',e=>{selectedImage=e.target.closest('img');$('imageInspector').hidden=!selectedImage;if(selectedImage){$('inlineImageWidth').value=selectedImage.width||450;$('inlineImageLayout').value=selectedImage.dataset.layout||'inline';}});
for(const id of ['inlineImageWidth','inlineImageLayout'])$(id).addEventListener('change',()=>{if(!selectedImage||!selectedImage.isConnected)return;selectedImage.width=Math.max(40,Math.min(674,Number($('inlineImageWidth').value)||450));selectedImage.dataset.layout=$('inlineImageLayout').value;changed();schedulePages();});$('removeInlineImage').addEventListener('click',()=>{selectedImage?.remove();selectedImage=null;$('imageInspector').hidden=true;changed();});
$('richEditor').addEventListener('dragstart',e=>{draggedImage=e.target.closest('img');});$('richEditor').addEventListener('dragover',e=>e.preventDefault());$('richEditor').addEventListener('drop',e=>{e.preventDefault();let range=document.caretRangeFromPoint?.(e.clientX,e.clientY);if(range&&$('richEditor').contains(range.startContainer))savedRange=range;const file=Array.from(e.dataTransfer.files).find(f=>f.type.startsWith('image/'));if(file){insertFile(file);return;}if(draggedImage&&$('richEditor').contains(draggedImage)){const insertion=restoreCaret();insertion.insertNode(draggedImage);draggedImage=null;changed();schedulePages();}});
for(const [text,align]of [['⇤','left'],['≡','center'],['⇥','right'],['☷','justify']])document.querySelector('.format-toolbar').appendChild(button(text,()=>{restoreCaret();let block=getSelection().anchorNode;while(block&&block!==$('richEditor')&&!['P','DIV','LI','TD','TH'].includes(block.nodeName))block=block.parentNode;if(block&&block!==$('richEditor'))block.setAttribute('align',align);changed();}));
async function snapshot(id){try{if(!doc)return;const element=$(id);let blob;if(element instanceof HTMLCanvasElement)blob=await new Promise(resolve=>element.toBlob(resolve,'image/png'));else{const svg=element.cloneNode(true);svg.setAttribute('xmlns',NS);const box=svg.viewBox.baseVal;svg.setAttribute('width',box.width);svg.setAttribute('height',box.height);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=node('canvas');canvas.width=box.width;canvas.height=box.height;const context=canvas.getContext('2d');context.fillStyle='#fffdf7';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0);blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}finally{URL.revokeObjectURL(url);}}if(!blob)throw Error('Immagine non generata.');await insertFile(new File([blob],id+'.png',{type:'image/png'}));}catch(e){error(e.message);}}
for(const [pane,id,title]of [['pane-circuit','circuitSvg','Inserisci circuito nel quaderno'],['pane-network','networkSvg','Inserisci topologia nel quaderno'],['pane-math','plotSvg','Inserisci grafico nel quaderno'],['pane-draw','drawingCanvas','Inserisci disegno nel quaderno']])$(pane).appendChild(button('▧ '+title,()=>snapshot(id)));
window.TramontoLab.insertExisting=insertExisting;window.TramontoLab.snapshot=snapshot;

for(const el of document.querySelectorAll('.table-tools,.word-insert'))$('pane-text').insertBefore(el,$('a4Frame'));
if(doc)openNote();
})();
