/* Study controls use the same checked expression as the plotted curve. */
(()=>{'use strict';
const M=TramontoMath,graph=$('plotSvg'),section=graph.closest('.math-section');let last=null,timer=0;
function button(id,label,action){const b=node('button',label);b.id=id;b.type='button';b.className='secondary-button';b.addEventListener('click',action);return b;}
function numeric(host,id,label,value){const wrap=node('label',label),field=node('input');field.id=id;field.type='number';field.step='any';field.min=-10000;field.max=10000;field.value=value;wrap.append(field);host.append(wrap);return field;}
const formulaGraph=button('formulaToGraph','Inserisci questa formula nel grafico',()=>setExpression($('formulaInput').value));$('cancelFormulaEdit').after(formulaGraph);
const calcGraph=button('calculusToGraph','Inserisci f(x) nel grafico',()=>setExpression($('calcExpression').value));$('calculateRoot').after(calcGraph);
const newFunction=node('div');newFunction.className='tool-actions';const input=node('input');input.id='graphNewExpression';input.placeholder='y = √(x−3) / √(x²−1), oppure LaTeX';input.maxLength=4000;input.setAttribute('aria-label','Nuova funzione del grafico');newFunction.append(input,button('graphAddExpression','+ Aggiungi curva',()=>setExpression(input.value,true)));$('plotExpressions').before(newFunction);
const controls=node('div');controls.className='tool-actions graph-study-controls';const fit=button('graphFitY','Adatta assi y',fitY);controls.append(fit);
const derivative=node('input');derivative.id='graphDerivative';derivative.type='checkbox';const derivativeLabel=node('label','Mostra derivata');derivativeLabel.prepend(derivative);controls.append(derivativeLabel);
const shade=node('input');shade.id='graphShadeArea';shade.type='checkbox';const shadeLabel=node('label','Evidenzia area');shadeLabel.prepend(shade);controls.append(shadeLabel);
const areaA=numeric(controls,'graphAreaFrom','Da x =',0),areaB=numeric(controls,'graphAreaTo','a x =',1);
controls.append(button('graphAreaVisible','Usa tratto visibile',()=>{try{const settings=graphSettings(),fn=expressionFunction(settings.expressions[0]),a=M.analyze(settings.expressions[0],fn);const interval=a.intervals.find(s=>s.hi>settings.x_min&&s.lo<settings.x_max);if(!interval)throw Error('Non ci sono tratti del dominio nell’intervallo visibile.');const lo=Math.max(settings.x_min,interval.lo),hi=Math.min(settings.x_max,interval.hi),eps=(hi-lo)/1000;areaA.value=lo+(lo===interval.lo&&!interval.lc?eps:0);areaB.value=hi-(hi===interval.hi&&!interval.hc?eps:0);plot(true);}catch(e){$('graphMessage').textContent=e.message;}}));graph.before(controls);
const actions=$('plotGraph').parentElement;const insertGraph=button('insertGraphNotebook','Inserisci grafico nel quaderno',async()=>{insertGraph.disabled=true;try{await TramontoLab.snapshot('plotSvg');}finally{insertGraph.disabled=false;}});actions.append(insertGraph);
actions.append(button('studyFunction','Studia funzione',()=>{if(!plot(true))try{const settings=graphSettings(),functions=settings.expressions.map(expressionFunction);renderStudy(settings,functions);}catch(e){$('graphMessage').textContent=e.message;}}));
const report=node('section');report.id='functionStudy';report.className='function-study';report.setAttribute('aria-label','Studio della prima funzione');section.append(report);
const reportActions=node('div');reportActions.className='tool-actions';reportActions.append(button('insertFunctionStudy','Inserisci studio nel quaderno',()=>{if(!plot(false)||!last)return;TramontoLab.insertHtml(notebookReport());}));section.append(reportActions);
const note=node('p','Dominio: condizioni reali e intervalli per vincoli polinomiali fino al secondo grado. Le condizioni non risolte restano esplicite. Zeri e segno delle altre funzioni, quadranti e aree sono stime nell’intervallo visibile. Integrali numerici: scegli un tratto continuo del dominio.');note.className='tool-note';section.append(note);
const examples=node('div');examples.className='graph-examples';for(const [name,value]of [['Il tuo esempio','sqrt(x-3)/sqrt(x^2-1)'],['Parabola','x^2-4'],['Frazione','(x+1)/(x-2)'],['Logaritmo','log(x)'],['Seno','sin(x)'],['Valore assoluto','abs(x-2)']])examples.append(button('',name,()=>setExpression(value)));newFunction.after(examples);
// A separate sign tool leaves graph and area settings independent.
const signTool=node('section');signTool.className='math-section';signTool.id='signStudyTool';
signTool.append(node('h3','Studia il segno.'));
const signLabel=node('label','f(x) · testo o LaTeX'),signInput=node('input');signInput.id='signExpression';signInput.value='(x+1)/(x-2)';signInput.maxLength=4000;signLabel.append(signInput);signTool.append(signLabel);
const signControls=node('div');signControls.className='tool-actions';const signFrom=numeric(signControls,'signFrom','Stima da x =',-10),signTo=numeric(signControls,'signTo','a x =',10);
signControls.append(button('calculateSign','Studia il segno',runSign),button('signFromGraph','Usa prima curva',()=>{signInput.value=$('plotExpressions').value.split('\n').find(x=>x.trim())||'';runSign();}));signTool.append(signControls);
const signExamples=node('div');signExamples.className='graph-examples';for(const [label,value]of [['Parabola','x^2-4'],['Frazione','(x+1)/(x-2)'],['Radice','sqrt(x-3)'],['Seno','sin(x)']])signExamples.append(button('',label,()=>{signInput.value=value;runSign();}));signTool.append(signExamples);
const signMessage=node('p');signMessage.id='signMessage';signMessage.setAttribute('role','status');const signResult=node('div');signResult.id='signResult';signResult.className='function-study';signTool.append(signMessage,signResult);
const signActions=node('div');signActions.className='tool-actions';const insertSign=button('insertSignStudy','Inserisci studio del segno nel quaderno',()=>{if(runSign())TramontoLab.insertHtml(signResult.innerHTML+'<p></p>');});insertSign.disabled=true;signActions.append(insertSign);signTool.append(signActions);
signTool.append(node('p','Per le funzioni risolte, il segno è studiato su tutto il dominio. Per le altre, la tabella è una stima numerica nel tratto scelto: può non rilevare tutti gli zeri o le discontinuità.'));section.before(signTool);
function runSign(){insertSign.disabled=true;signResult.replaceChildren();signMessage.textContent='';try{
 const expression=M.normalize(signInput.value),fn=expressionFunction(expression),a=Number(signFrom.value),b=Number(signTo.value);
 if(!signFrom.value.trim()||!signTo.value.trim()||!Number.isFinite(a)||!Number.isFinite(b)||a>=b||Math.abs(a)>10000||Math.abs(b)>10000)throw Error('Scegli un intervallo crescente tra −10000 e 10000.');
 const study=M.study(expression,fn,a,b);signResult.append(node('h3','Studio del segno di f(x) = '+expression),node('p','Dominio reale: '+study.domain));
 signResult.append(node('p',study.exact?'Studio su tutto il dominio.':'Stima numerica per x ∈ ['+M.format(a)+'; '+M.format(b)+']. Zeri e discontinuità possono non essere tutti rilevati.'));
 const isZero=x=>study.zeros.some(z=>Math.abs(z-x)<1e-8*Math.max(1,Math.abs(x)));
 const ranges=[];for(const s of study.signs){const previous=ranges.at(-1);if(previous&&previous.hi===s.lo&&previous.sign===s.sign&&study.allowed(s.lo)&&Number.isFinite(fn(s.lo))&&fn(s.lo)!==0&&!isZero(s.lo))previous.hi=s.hi;else ranges.push({...s});}
 const included=x=>Number.isFinite(x)&&study.allowed(x)&&Number.isFinite(fn(x))&&fn(x)!==0&&!isZero(x);
 const interval=s=>study.intervalText({lo:s.lo,hi:s.hi,lc:included(s.lo),hc:included(s.hi)});
 const intervals=sign=>ranges.filter(s=>s.sign===sign).map(interval).join(' ∪ ')||'Nessun intervallo'+(study.exact?'':' rilevato');
 signResult.append(node('p','f(x) > 0: '+intervals('+')),node('p','f(x) < 0: '+intervals('−')),node('p','f(x) = 0: '+(study.zero.zero?'Tutto il dominio':study.zeros.map(M.format).join(' · ')||(study.exact?'Nessuno':'Nessuno rilevato'))));
 const excluded=study.cuts.filter(x=>!study.allowed(x));if(excluded.length)signResult.append(node('p','Punti esclusi dal dominio: '+excluded.map(M.format).join(' · ')));
 signResult.append(table(['Intervallo','Segno di f(x)'],ranges.map(s=>[interval(s),s.sign])));
 signResult.append(node('p','Gli zeri appartengono al dominio; i punti esclusi non sono soluzioni. Consulta il dominio anche per gli estremi degli intervalli.'));insertSign.disabled=false;return true;
 }catch(e){signMessage.textContent=e.message;return false;}}
signInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runSign();}});
for(const field of [signInput,signFrom,signTo])field.addEventListener('input',()=>{signResult.replaceChildren();signMessage.textContent='';insertSign.disabled=true;});
const manual=node('section');manual.id='manualSignTool';manual.className='math-section';manual.append(node('h3','Tabella del segno · compila tu.'),node('p','Inserisci i punti critici, poi scegli il segno dei fattori nei tratti e nei punti. Il risultato combina i segni: uno zero al denominatore esclude il punto.'));
const manualControls=node('div');manualControls.className='tool-actions';const cutLabel=node('label','Punti critici (separati da ;)'),cutInput=node('input');cutInput.id='signCriticalValues';cutInput.value='-1; 2';cutInput.maxLength=200;cutInput.placeholder='-2; 0; 3';cutLabel.append(cutInput);manualControls.append(cutLabel,button('signBuildTable','Crea tabella',buildManual));manual.append(manualControls);
const manualMessage=node('p');manualMessage.id='manualSignMessage';manualMessage.className='tool-message';manualMessage.setAttribute('role','status');const manualEditor=node('div');manualEditor.id='manualSignEditor';manualEditor.className='sign-table-scroll';manual.append(manualMessage,manualEditor);
const manualActions=node('div');manualActions.className='tool-actions';manualActions.append(button('signAddFactor','+ Fattore',()=>{if(!manualState||manualState.rows.length>=6){manualMessage.textContent='Puoi usare al massimo sei fattori.';return;}manualState.rows.push({label:'Fattore '+(manualState.rows.length+1),role:'factor',signs:Array(manualState.cuts.length*2+1).fill('?')});renderManual();saveManual();}),button('signManualExample','Esempio frazione',()=>{cutInput.value='-1; 2';manualState={cuts:[-1,2],labels:['-1','2'],rows:[{label:'x + 1',role:'factor',signs:['−','0','+','+','+']},{label:'x − 2',role:'denominator',signs:['−','−','−','0','+']}]};renderManual();saveManual();}));manual.append(manualActions);
const manualSvg=svgNode('svg',{id:'manualSignSvg',viewBox:'0 0 800 230',role:'img','aria-label':'Diagramma dello studio del segno compilato a mano',class:'manual-sign-diagram'});const manualPreview=node('div');manualPreview.className='sign-table-scroll manual-sign-preview';manualPreview.append(manualSvg);manual.append(manualPreview);
const manualInsert=button('insertManualSign','Inserisci tabella nel quaderno',async()=>{manualInsert.disabled=true;try{await TramontoLab.snapshot('manualSignSvg');}finally{manualInsert.disabled=false;}});manual.append(manualInsert,node('p','? = da compilare · × = fuori dominio. I fattori e i segni li scegli tu; non vengono ricavati automaticamente dalle etichette. La bozza resta su questo browser per la pagina; inserisci la tabella per salvarla nel quaderno.'));signTool.before(manual);
let manualState=null;
function saveManual(){if(!doc||!manualState)return;try{localStorage.setItem('alba.signChart.'+doc.id,JSON.stringify(manualState));}catch(_){manualMessage.textContent='Bozza locale non disponibile: inserisci la tabella nel quaderno per conservarla.';}}
function buildManual(){try{const labels=cutInput.value.split(';').map(s=>s.trim()).filter(Boolean);if(labels.length>6)throw Error('Inserisci al massimo sei punti critici.');const cuts=labels.map(s=>{const value=M.normalize(s);math.parse(value).traverse(n=>{if(n.type==='SymbolNode'&&n.name==='x')throw Error('I punti critici devono essere valori, senza x.');});const x=expressionFunction(value)(0);if(!Number.isFinite(x)||Math.abs(x)>10000)throw Error('Usa valori reali tra −10000 e 10000.');return x;});if(cuts.some((x,i)=>i&&x<=cuts[i-1]))throw Error('Scrivi i punti in ordine crescente, senza ripetizioni.');const same=manualState&&JSON.stringify(cuts)===JSON.stringify(manualState.cuts);manualState={cuts,labels,rows:same?manualState.rows:[{label:'Fattore 1',role:'factor',signs:Array(cuts.length*2+1).fill('?')}]};manualMessage.textContent='';renderManual();saveManual();}catch(e){manualMessage.textContent=e.message;}}
function combinedSigns(){return Array.from({length:manualState.cuts.length*2+1},(_,i)=>{const signs=manualState.rows.map(r=>r.signs[i]);if(signs.includes('×')||manualState.rows.some(r=>r.role==='denominator'&&r.signs[i]==='0'))return '×';if(signs.includes('?'))return '?';if(signs.includes('0'))return '0';return signs.filter(s=>s==='−').length%2?'−':'+';});}
function manualHeaders(){const {cuts,labels}=manualState;return Array.from({length:cuts.length*2+1},(_,i)=>i%2?labels[(i-1)/2]:'('+(i===0?'−∞':labels[i/2-1])+'; '+(i===cuts.length*2?'+∞':labels[i/2])+')');}
function renderManual(){if(!manualState)return;manualEditor.replaceChildren();const headers=manualHeaders(),t=node('table');t.className='lab-table manual-sign-table';const head=node('tr');head.append(node('th','Fattore'));headers.forEach(h=>head.append(node('th',h)));t.append(head);
 for(const [index,row]of manualState.rows.entries()){const tr=node('tr'),labelCell=node('td'),label=node('input');label.value=row.label;label.maxLength=50;label.setAttribute('aria-label','Nome del fattore '+(index+1));label.addEventListener('input',()=>{row.label=label.value;drawManual();saveManual();});const role=node('select');role.setAttribute('aria-label','Ruolo del fattore '+(index+1));for(const [value,text]of [['factor','Fattore / numeratore'],['denominator','Denominatore']]){const o=node('option',text);o.value=value;role.append(o);}role.value=row.role;role.addEventListener('change',()=>{row.role=role.value;updateManualResult();});labelCell.append(label,role,button('','Rimuovi',()=>{if(manualState.rows.length===1)return;manualState.rows.splice(index,1);renderManual();saveManual();}));tr.append(labelCell);
  for(const [i,sign]of row.signs.entries()){const cell=node('td'),select=node('select');select.setAttribute('aria-label',row.label+' · '+headers[i]);for(const s of ['?','+','−','0','×']){const o=node('option',s);o.value=s;select.append(o);}select.value=sign;select.dataset.row=index;select.dataset.column=i;select.addEventListener('change',()=>{row.signs[i]=select.value;updateManualResult();});cell.append(select);tr.append(cell);}t.append(tr);
 }const result=node('tr');result.id='manualSignResult';t.append(result);manualEditor.append(t);updateManualResult();}
function updateManualResult(){const result=$('manualSignResult');result.replaceChildren(node('th','Risultato'));combinedSigns().forEach(s=>result.append(node('td',s)));drawManual();saveManual();}
function drawManual(){const rows=[...manualState.rows,{label:'Risultato',role:'result',signs:combinedSigns()}],height=110+rows.length*48,n=manualState.cuts.length*2+1,left=150,right=775,step=(right-left)/n;manualSvg.setAttribute('viewBox','0 0 800 '+height);manualSvg.replaceChildren();const font=doc?.content.font==='custom'?'TramontoPersonal, Georgia, serif':'Georgia, serif';manualSvg.setAttribute('font-family',font);manualSvg.append(svgNode('rect',{width:800,height,fill:'#fffdf7'}),svgNode('text',{x:20,y:28,fill:'#263c31','font-size':20},'Studio del segno · tabella compilata'));
 const boundaries=manualState.cuts.map((x,i)=>left+step*(2*i+1.5));manualSvg.append(svgNode('line',{x1:left,y1:65,x2:right,y2:65,stroke:'#788275'}));manualSvg.append(svgNode('text',{x:left,y:53,fill:'#263c31','font-size':14},'−∞'),svgNode('text',{x:right,y:53,'text-anchor':'end',fill:'#263c31','font-size':14},'+∞'));
 boundaries.forEach((x,i)=>{manualSvg.append(svgNode('line',{x1:x,y1:60,x2:x,y2:height-20,stroke:'#ccd3c6','stroke-dasharray':'3 4'}),svgNode('text',{x,y:53,'text-anchor':'middle',fill:'#263c31','font-size':14},manualState.labels[i].length>12?M.format(manualState.cuts[i]):manualState.labels[i]));});
 rows.forEach((row,r)=>{const y=100+r*48;manualSvg.append(svgNode('text',{x:16,y:y+5,fill:'#263c31','font-size':14},(row.role==='denominator'?'D: ':'')+(Array.from(row.label).length>17?Array.from(row.label).slice(0,16).join('')+'…':row.label)));if(row.role==='result')manualSvg.append(svgNode('line',{x1:15,y1:y-24,x2:right,y2:y-24,stroke:'#788275'}));row.signs.forEach((sign,i)=>{const x=left+(i+.5)*step;if(i%2===0&&['+','−'].includes(sign)){manualSvg.append(svgNode('line',{x1:i===0?left:boundaries[i/2-1],y1:y,x2:i===n-1?right:boundaries[i/2],y2:y,stroke:'#456b43','stroke-width':row.role==='result'?2.5:1.5,...(sign==='−'?{'stroke-dasharray':'5 4'}:{})}),svgNode('text',{x,y:y-7,'text-anchor':'middle',fill:'#263c31','font-size':16},sign));}else if(sign==='0'){manualSvg.append(svgNode('circle',{cx:x,cy:y,r:5,fill:'#fffdf7',stroke:'#456b43','stroke-width':1.5}),svgNode('text',{x,y:y-10,'text-anchor':'middle',fill:'#263c31','font-size':12},'0'));}else manualSvg.append(svgNode('text',{x,y:y+5,'text-anchor':'middle',fill:sign==='×'?'#a54434':'#788275','font-size':16},sign));});});}
function loadManual(){manualState=null;manualMessage.textContent='';try{const saved=doc&&JSON.parse(localStorage.getItem('alba.signChart.'+doc.id));if(saved&&Array.isArray(saved.cuts)&&saved.cuts.length<=6&&saved.cuts.every((x,i)=>Number.isFinite(x)&&Math.abs(x)<=10000&&(!i||x>saved.cuts[i-1]))&&Array.isArray(saved.labels)&&saved.labels.length===saved.cuts.length&&saved.labels.every(s=>typeof s==='string'&&s.length<=200)&&Array.isArray(saved.rows)&&saved.rows.length&&saved.rows.length<=6&&saved.rows.every(r=>typeof r.label==='string'&&r.label.length<=50&&['factor','denominator'].includes(r.role)&&Array.isArray(r.signs)&&r.signs.length===saved.cuts.length*2+1&&r.signs.every(s=>['?','+','−','0','×'].includes(s))))manualState=saved;}catch(_){}if(manualState){cutInput.value=manualState.labels.join('; ');renderManual();}else{cutInput.value='-1; 2';buildManual();}}
function options(){const from=Number(areaA.value),to=Number(areaB.value);if(!Number.isFinite(from)||!Number.isFinite(to)||from>=to||Math.abs(from)>10000||Math.abs(to)>10000)throw Error('Per l’area scegli estremi finiti a < b tra −10000 e 10000.');return {show_area:shade.checked,show_derivative:derivative.checked,area_from:from,area_to:to};}
function setExpression(value,append=false){try{const expression=M.normalize(value);expressionFunction(expression);const values=append?$('plotExpressions').value.split('\n').map(x=>x.trim()).filter(Boolean):[];if(values.length>=3)throw Error('Puoi tracciare al massimo tre curve.');values.push(expression);$('plotExpressions').value=values.join('\n');document.querySelector('[data-pane=math]').click();openTool('graph');fitY();graph.scrollIntoView({block:'center'});}catch(e){$('graphMessage').textContent=e.message;}}
function fitY(){try{const settings=graphSettings(),values=[];for(const expression of settings.expressions){const fn=expressionFunction(expression);for(let i=0;i<=600;i++){const y=fn(settings.x_min+(settings.x_max-settings.x_min)*i/600);if(Number.isFinite(y)&&Math.abs(y)<1e8)values.push(y);}}if(!values.length){plot(false);return;}values.sort((a,b)=>a-b);const lo=Math.min(0,values[Math.floor(values.length*.02)]),hi=Math.max(0,values[Math.floor((values.length-1)*.98)]),padding=Math.max(.2,(hi-lo)*.12);$('yMin').value=Math.max(-10000,Math.floor((lo-padding)*100)/100);$('yMax').value=Math.min(10000,Math.ceil((hi+padding)*100)/100);if(Number($('yMin').value)>=Number($('yMax').value))throw Error('I valori sono troppo grandi: cambia l’intervallo di x.');plot(true);}catch(e){$('graphMessage').textContent=e.message;}}
function drawArea(settings,functions,svg,px,py){const opts=options();if(!opts.show_area)return;const fn=functions[0];let points=[];function finish(){if(points.length>1){const path='M'+px(points[0][0])+' '+py(0)+points.map(([x,y])=>' L'+px(x)+' '+py(y)).join('')+' L'+px(points.at(-1)[0])+' '+py(0)+' Z';svg.append(svgNode('path',{d:path,fill:'#d58c5745',stroke:'none','clip-path':'url(#plotClip)','data-shaded-area':'true'}));}points=[];}
 const a=Math.max(settings.x_min,opts.area_from),b=Math.min(settings.x_max,opts.area_to);if(a>=b)return;for(let i=0;i<=500;i++){const x=a+(b-a)*i/500,y=fn(x);if(!Number.isFinite(y)||Math.abs(py(y))>1e6){finish();continue;}if(points.length&&Math.abs(py(y)-py(points.at(-1)[1]))>340)finish();points.push([x,y]);}finish();}
function onPlot(settings,functions,svg,px,py){renderStudy(settings,functions);if(!derivative.checked||!last)return;try{const fn=expressionFunction(last.analysis.derivative);let path='',previous=null;for(let i=0;i<=600;i++){const x=settings.x_min+(settings.x_max-settings.x_min)*i/600,y=fn(x),p=py(y);if(!last.analysis.allowed(x)||!Number.isFinite(y)||Math.abs(p)>1e6){previous=null;continue;}path+=(previous!==null&&Math.abs(p-previous)<280?' L':' M')+px(x).toFixed(2)+' '+p.toFixed(2);previous=p;}svg.append(svgNode('path',{d:path,stroke:'#3159a4','stroke-width':1.6,'stroke-dasharray':'6 4',fill:'none','clip-path':'url(#plotClip)','data-derivative':'true'}));svg.append(svgNode('text',{x:735,y:15,'text-anchor':'end',fill:'#3159a4','font-size':11},'f′(x)'));}catch(_){$('graphMessage').textContent+=' · Derivata disponibile nel riepilogo; non tracciabile con questi comandi.';}}
function addCard(host,title,value,id){const card=node('div');card.className='study-card';card.append(node('h4',title));const text=node('p',value);if(id)text.id=id;card.append(text);host.append(card);return card;}
function table(headers,rows){const t=node('table');t.className='lab-table';const head=node('tr');headers.forEach(h=>head.append(node('th',h)));t.append(head);for(const row of rows){const tr=node('tr');row.forEach(x=>tr.append(node('td',String(x))));t.append(tr);}return t;}
function renderStudy(settings,functions){const expression=settings.expressions[0],fn=functions[0],analysis=M.study(expression,fn,settings.x_min,settings.x_max);let area=null,areaError='';const opts=options();try{area=M.integrate(fn,opts.area_from,opts.area_to,analysis.allowed);}catch(e){areaError=e.message;}
 last={expression,settings,analysis,area,areaError,options:opts};report.replaceChildren(node('h3','Studio di f(x) = '+expression));const cards=node('div');cards.className='study-cards';report.append(cards);
 addCard(cards,'Dominio reale',analysis.domain,'studyDomain');addCard(cards,'Zeri',analysis.zero.zero?'Tutto il dominio':analysis.zeros.length?analysis.zeros.map(M.format).join(' · '):analysis.exact?'Nessuno':'Nessuno rilevato nei campioni','studyZeros');addCard(cards,'Intersezione con l’asse y',analysis.yIntercept===null?'x = 0 fuori dal dominio':'(0; '+M.format(analysis.yIntercept)+')','studyYIntercept');
 const quadrants=addCard(cards,'Quadranti occupati nel tratto visibile',analysis.quadrants.join(' · ')||'Solo assi o nessun punto reale','studyQuadrants');const diagram=svgNode('svg',{viewBox:'0 0 120 120',class:'quadrants-diagram',role:'img','aria-label':'Quadranti occupati: '+analysis.quadrants.join(', ')});for(const [name,x,y]of [['I',60,0],['II',0,0],['III',0,60],['IV',60,60]]){diagram.append(svgNode('rect',{x,y,width:60,height:60,fill:analysis.quadrants.includes(name)?'#456b4340':'#87998010'}));diagram.append(svgNode('text',{x:x+30,y:y+34,'text-anchor':'middle',fill:'#263c31','font-size':14},name));}diagram.append(svgNode('path',{d:'M60 0V120M0 60H120',stroke:'#879980'}));quadrants.append(diagram);
 addCard(cards,'Area tra a e b',area?'Area geometrica ≈ '+M.format(area.absolute)+' · integrale con segno ≈ '+M.format(area.signed):areaError,'studyArea');
 report.append(node('h4',analysis.exact?'Studio del segno':'Segno stimato nel tratto visibile'));report.append(table(['Intervallo','f(x)'],analysis.signs.map(s=>['('+M.format(s.lo)+'; '+M.format(s.hi)+')',s.sign])));report.append(node('p','Nei punti elencati tra gli zeri, f(x) = 0. I punti fuori dal dominio sono esclusi.'));
 report.append(node('h4','Derivata simbolica'),node('pre',analysis.derivative));report.append(node('h4','Tabella di valori'));const values=Array.from({length:7},(_,i)=>{const x=settings.x_min+(settings.x_max-settings.x_min)*i/6,y=fn(x);return [M.format(x),Number.isFinite(y)&&analysis.allowed(x)?M.format(y):'fuori dominio'];});report.append(table(['x','f(x)'],values));
}
function notebookReport(){const host=node('div');host.append(node('h3','Studio di f(x) = '+last.expression),node('p','Dominio reale: '+last.analysis.domain),node('p','Zeri: '+(last.analysis.zero.zero?'tutto il dominio':last.analysis.zeros.map(M.format).join(', ')||'nessuno rilevato')),node('p','Quadranti nel tratto visibile: '+(last.analysis.quadrants.join(', ')||'solo assi')),node('p','Derivata: '+last.analysis.derivative));host.append(table(['Intervallo',last.analysis.exact?'Segno':'Segno stimato'],last.analysis.signs.map(s=>['('+M.format(s.lo)+'; '+M.format(s.hi)+')',s.sign])));if(last.area)host.append(node('p','Da '+M.format(last.options.area_from)+' a '+M.format(last.options.area_to)+': area geometrica ≈ '+M.format(last.area.absolute)+'; integrale ≈ '+M.format(last.area.signed)+'.'));host.append(node('p',last.analysis.exact?'Quadranti e integrali sono stime numeriche nel tratto visibile.':'Zeri, segno, quadranti e integrali sono stime numeriche nel tratto visibile.'),node('p'));return host.innerHTML;}
for(const e of [derivative,shade,areaA,areaB])e.addEventListener('change',()=>plot(true));
for(const e of [$('plotExpressions'),$('xMin'),$('xMax'),$('yMin'),$('yMax')])e.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>plot(false),450);});
function load(){clearTimeout(timer);last=null;report.replaceChildren();signResult.replaceChildren();signMessage.textContent='';insertSign.disabled=true;loadManual();const saved=doc?.content.graph.study;shade.checked=saved?.show_area||false;derivative.checked=saved?.show_derivative||false;areaA.value=saved?.area_from??0;areaB.value=saved?.area_to??1;if(doc&&activePane==='math')plot(false);}
TramontoLab.insertHtml=html=>{document.querySelector('[data-pane=text]').click();TramontoLab.insertReportHtml(html);};
function clear(){last=null;report.replaceChildren();signResult.replaceChildren();signMessage.textContent='';insertSign.disabled=true;}
// Keep one tool open at a time; existing controls retain their ids and handlers.
const mathStage=$('pane-math').querySelector('.tool-stage'),panels=new Map();
function panel(key,title,elements){const details=node('details');details.className='math-tool-panel';details.setAttribute('name','tramonto-math-tools');details.dataset.mathTool=key;const summary=node('summary',title);summary.addEventListener('click',event=>{event.preventDefault();if(details.open)details.open=false;else openTool(key);});details.append(summary);const body=node('div');body.className='math-tool-body';body.append(...elements);details.append(body);panels.set(key,details);details.addEventListener('toggle',()=>{if(details.open)for(const other of panels.values())if(other!==details)other.open=false;});return details;}
const formulaElements=[];for(const child of [...mathStage.children]){if(child.classList.contains('math-section'))break;formulaElements.push(child);}
const formulaPanel=panel('formulas','Formule · la tua scrittura',formulaElements),manualPanel=panel('manual','Tabella del segno · compila tu', [manual]),signPanel=panel('sign','Studio del segno · da una funzione',[signTool]),graphPanel=panel('graph','Grafico e studio della funzione',[section]);
const others=[...mathStage.children].filter(e=>e.classList.contains('math-section'));
mathStage.append(formulaPanel,manualPanel,signPanel,graphPanel);for(const e of others){const isLimit=!!e.querySelector('#limitExpression');mathStage.append(panel(isLimit?'limits':'calculus',isLimit?'Limiti':'Valori, derivate e integrali',[e]));}
for(const b of [...mathStage.children])if(b.tagName==='BUTTON'&&b.textContent.includes('Inserisci grafico nel quaderno'))b.remove();
function openTool(key){const selected=panels.get(key);if(!selected)return;for(const details of panels.values())details.open=details===selected;}
document.querySelector('.formula-snippets').addEventListener('click',()=>openTool('formulas'),true);
openTool('formulas');$('noteFont').addEventListener('change',()=>{if(manualState)drawManual();});document.addEventListener('tramonto:font-ready',()=>{if(manualState)drawManual();});
window.TramontoStudy={options,onPlot,drawArea,load,setExpression,fitY,clear,openTool};load();
})();
