"""Executed only inside the isolated learning workspace."""
import json
import resource
import runpy
import sys
from pathlib import Path

resource.setrlimit(resource.RLIMIT_CPU, (5, 5))
resource.setrlimit(resource.RLIMIT_AS, (256*1024*1024, 256*1024*1024))
resource.setrlimit(resource.RLIMIT_FSIZE, (1024*1024, 1024*1024))
resource.setrlimit(resource.RLIMIT_NOFILE, (32, 32))
resource.setrlimit(resource.RLIMIT_NPROC, (16, 16))
resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
if len(sys.argv)>1:
    tool=sys.argv[1]
    if tool not in ('ruff','bandit','pytest'): raise ValueError('Strumento non valido')
    sys.path[:0]=[str(p) for p in Path('/tools/lib').glob('python*/site-packages')]
    if tool=='ruff': sys.argv=['ruff','check','/work/solution.py','--output-format','concise']
    elif tool=='bandit': sys.argv=['bandit','-q','-r','/work/solution.py']
    else: sys.argv=['pytest','-q','-p','no:cacheprovider','/work/test_solution.py']
    runpy.run_module(tool,run_name='__main__')
    raise SystemExit(0)
# Tests are maintained by the runtime, not generated by the model.
spec = json.loads(Path('/work/spec.json').read_text())
namespace = runpy.run_path('/work/solution.py')
if not spec.get('function'):
    raise SystemExit(0)
function = namespace.get(spec['function'])
if not callable(function): raise ValueError('Funzione richiesta assente')
for case in spec['cases']:
    actual = function(*case['args'])
    assert actual == case['expected'], f"Atteso {case['expected']!r}, ottenuto {actual!r}"
print(f"PASS: {len(spec['cases'])} casi indipendenti")
